// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: arch.sql

package dbq

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const archKindExists = `-- name: ArchKindExists :one
SELECT EXISTS (SELECT 1 FROM arch_node_kinds WHERE project_id = $1 AND key = $2) AS ok
`

type ArchKindExistsParams struct {
	ProjectID uuid.UUID
	Key       string
}

func (q *Queries) ArchKindExists(ctx context.Context, arg ArchKindExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, archKindExists, arg.ProjectID, arg.Key)
	var ok bool
	err := row.Scan(&ok)
	return ok, err
}

const archNodeCycleCheck = `-- name: ArchNodeCycleCheck :one
WITH RECURSIVE
ancestors(id) AS (
    SELECT id FROM arch_nodes WHERE id = $1::uuid
    UNION
    SELECT a.parent_id FROM arch_nodes a
    JOIN ancestors r ON r.id = a.id
    WHERE a.parent_id IS NOT NULL
),
descendants(id) AS (
    SELECT id FROM arch_nodes WHERE id = $2::uuid
    UNION
    SELECT a.id FROM arch_nodes a
    JOIN descendants d ON d.id = a.parent_id
    WHERE a.project_id = $3::uuid
)
SELECT EXISTS (
    SELECT 1 FROM ancestors anc
    JOIN descendants d ON d.id = anc.id
) AS hit
`

type ArchNodeCycleCheckParams struct {
	NewParentID uuid.UUID
	NodeID      uuid.UUID
	ProjectID   uuid.UUID
}

func (q *Queries) ArchNodeCycleCheck(ctx context.Context, arg ArchNodeCycleCheckParams) (bool, error) {
	row := q.db.QueryRow(ctx, archNodeCycleCheck, arg.NewParentID, arg.NodeID, arg.ProjectID)
	var hit bool
	err := row.Scan(&hit)
	return hit, err
}

const countArchKinds = `-- name: CountArchKinds :one
SELECT COUNT(*)::int AS n FROM arch_node_kinds WHERE project_id = $1
`

func (q *Queries) CountArchKinds(ctx context.Context, projectID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, countArchKinds, projectID)
	var n int32
	err := row.Scan(&n)
	return n, err
}

const countArchNodeChildren = `-- name: CountArchNodeChildren :one
SELECT COUNT(*)::int AS n FROM arch_nodes WHERE parent_id = $1
`

func (q *Queries) CountArchNodeChildren(ctx context.Context, parentID *uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, countArchNodeChildren, parentID)
	var n int32
	err := row.Scan(&n)
	return n, err
}

const countNodesByKind = `-- name: CountNodesByKind :one
SELECT COUNT(*)::int AS n FROM arch_nodes WHERE project_id = $1 AND kind = $2
`

type CountNodesByKindParams struct {
	ProjectID uuid.UUID
	Kind      string
}

func (q *Queries) CountNodesByKind(ctx context.Context, arg CountNodesByKindParams) (int32, error) {
	row := q.db.QueryRow(ctx, countNodesByKind, arg.ProjectID, arg.Kind)
	var n int32
	err := row.Scan(&n)
	return n, err
}

const deleteArchEdge = `-- name: DeleteArchEdge :execrows
DELETE FROM arch_edges WHERE project_id = $1 AND id = $2
`

type DeleteArchEdgeParams struct {
	ProjectID uuid.UUID
	ID        uuid.UUID
}

func (q *Queries) DeleteArchEdge(ctx context.Context, arg DeleteArchEdgeParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteArchEdge, arg.ProjectID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteArchKind = `-- name: DeleteArchKind :execrows
DELETE FROM arch_node_kinds WHERE project_id = $1 AND key = $2
`

type DeleteArchKindParams struct {
	ProjectID uuid.UUID
	Key       string
}

func (q *Queries) DeleteArchKind(ctx context.Context, arg DeleteArchKindParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteArchKind, arg.ProjectID, arg.Key)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteArchNode = `-- name: DeleteArchNode :exec
DELETE FROM arch_nodes WHERE id = $1
`

func (q *Queries) DeleteArchNode(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteArchNode, id)
	return err
}

const deleteArchNodeLink = `-- name: DeleteArchNodeLink :exec
DELETE FROM arch_node_links
WHERE project_id = $1 AND node_id = $2 AND link_type = $3 AND target_id = $4
`

type DeleteArchNodeLinkParams struct {
	ProjectID uuid.UUID
	NodeID    uuid.UUID
	LinkType  string
	TargetID  string
}

func (q *Queries) DeleteArchNodeLink(ctx context.Context, arg DeleteArchNodeLinkParams) error {
	_, err := q.db.Exec(ctx, deleteArchNodeLink,
		arg.ProjectID,
		arg.NodeID,
		arg.LinkType,
		arg.TargetID,
	)
	return err
}

const getArchNodeBySlug = `-- name: GetArchNodeBySlug :one
SELECT id, project_id, slug, parent_id, kind, name, description_md,
       metadata, linked_repo, linked_path, position, created_at, updated_at
FROM arch_nodes
WHERE project_id = $1 AND slug = $2
`

type GetArchNodeBySlugParams struct {
	ProjectID uuid.UUID
	Slug      string
}

type GetArchNodeBySlugRow struct {
	ID            uuid.UUID
	ProjectID     uuid.UUID
	Slug          string
	ParentID      *uuid.UUID
	Kind          string
	Name          string
	DescriptionMd string
	Metadata      []byte
	LinkedRepo    pgtype.Text
	LinkedPath    pgtype.Text
	Position      int32
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
}

func (q *Queries) GetArchNodeBySlug(ctx context.Context, arg GetArchNodeBySlugParams) (GetArchNodeBySlugRow, error) {
	row := q.db.QueryRow(ctx, getArchNodeBySlug, arg.ProjectID, arg.Slug)
	var i GetArchNodeBySlugRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Slug,
		&i.ParentID,
		&i.Kind,
		&i.Name,
		&i.DescriptionMd,
		&i.Metadata,
		&i.LinkedRepo,
		&i.LinkedPath,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getArchNodeIDBySlug = `-- name: GetArchNodeIDBySlug :one
SELECT id FROM arch_nodes WHERE project_id = $1 AND slug = $2
`

type GetArchNodeIDBySlugParams struct {
	ProjectID uuid.UUID
	Slug      string
}

func (q *Queries) GetArchNodeIDBySlug(ctx context.Context, arg GetArchNodeIDBySlugParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getArchNodeIDBySlug, arg.ProjectID, arg.Slug)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const insertArchNode = `-- name: InsertArchNode :one
INSERT INTO arch_nodes (project_id, slug, parent_id, kind, name, description_md,
                        metadata, linked_repo, linked_path, position,
                        created_by_user_id, created_by_token_id,
                        updated_by_user_id, updated_by_token_id)
VALUES (
    $1::uuid,
    $2::text,
    $3::uuid,
    $4::text,
    $5::text,
    $6::text,
    $7::jsonb,
    $8::text,
    $9::text,
    $10::int,
    $11::uuid,
    $12::uuid,
    $11::uuid,
    $12::uuid
)
RETURNING id, project_id, slug, parent_id, kind, name, description_md,
          metadata, linked_repo, linked_path, position,
          created_at, updated_at
`

type InsertArchNodeParams struct {
	ProjectID     uuid.UUID
	Slug          string
	ParentID      *uuid.UUID
	Kind          string
	Name          string
	DescriptionMd string
	Metadata      []byte
	LinkedRepo    pgtype.Text
	LinkedPath    pgtype.Text
	Position      int32
	AuthorUserID  *uuid.UUID
	AuthorTokenID *uuid.UUID
}

type InsertArchNodeRow struct {
	ID            uuid.UUID
	ProjectID     uuid.UUID
	Slug          string
	ParentID      *uuid.UUID
	Kind          string
	Name          string
	DescriptionMd string
	Metadata      []byte
	LinkedRepo    pgtype.Text
	LinkedPath    pgtype.Text
	Position      int32
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
}

func (q *Queries) InsertArchNode(ctx context.Context, arg InsertArchNodeParams) (InsertArchNodeRow, error) {
	row := q.db.QueryRow(ctx, insertArchNode,
		arg.ProjectID,
		arg.Slug,
		arg.ParentID,
		arg.Kind,
		arg.Name,
		arg.DescriptionMd,
		arg.Metadata,
		arg.LinkedRepo,
		arg.LinkedPath,
		arg.Position,
		arg.AuthorUserID,
		arg.AuthorTokenID,
	)
	var i InsertArchNodeRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Slug,
		&i.ParentID,
		&i.Kind,
		&i.Name,
		&i.DescriptionMd,
		&i.Metadata,
		&i.LinkedRepo,
		&i.LinkedPath,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertArchNodeLink = `-- name: InsertArchNodeLink :exec
INSERT INTO arch_node_links (project_id, node_id, link_type, target_id)
VALUES ($1, $2, $3, $4)
ON CONFLICT DO NOTHING
`

type InsertArchNodeLinkParams struct {
	ProjectID uuid.UUID
	NodeID    uuid.UUID
	LinkType  string
	TargetID  string
}

func (q *Queries) InsertArchNodeLink(ctx context.Context, arg InsertArchNodeLinkParams) error {
	_, err := q.db.Exec(ctx, insertArchNodeLink,
		arg.ProjectID,
		arg.NodeID,
		arg.LinkType,
		arg.TargetID,
	)
	return err
}

const insertDefaultArchKind = `-- name: InsertDefaultArchKind :exec
INSERT INTO arch_node_kinds (project_id, key, label, icon, color, description, is_default)
VALUES ($1, $2, $3, $4, $5, $6, true)
ON CONFLICT DO NOTHING
`

type InsertDefaultArchKindParams struct {
	ProjectID   uuid.UUID
	Key         string
	Label       string
	Icon        string
	Color       string
	Description string
}

func (q *Queries) InsertDefaultArchKind(ctx context.Context, arg InsertDefaultArchKindParams) error {
	_, err := q.db.Exec(ctx, insertDefaultArchKind,
		arg.ProjectID,
		arg.Key,
		arg.Label,
		arg.Icon,
		arg.Color,
		arg.Description,
	)
	return err
}

const listArchEdges = `-- name: ListArchEdges :many
SELECT e.id, e.project_id, e.from_node_id, e.to_node_id, e.kind, e.label, e.description_md,
       e.created_at, e.updated_at,
       a.slug AS from_slug, a.name AS from_name,
       b.slug AS to_slug,   b.name AS to_name
FROM arch_edges e
JOIN arch_nodes a ON a.id = e.from_node_id
JOIN arch_nodes b ON b.id = e.to_node_id
WHERE e.project_id = $1
  AND ($2::text IS NULL OR e.kind = $2::text)
  AND ($3::uuid IS NULL
       OR ($4::text = 'out' AND e.from_node_id = $3::uuid)
       OR ($4::text = 'in'  AND e.to_node_id   = $3::uuid)
       OR ($4::text NOT IN ('out','in')
           AND (e.from_node_id = $3::uuid
                OR e.to_node_id = $3::uuid)))
ORDER BY e.kind, a.slug, b.slug
`

type ListArchEdgesParams struct {
	ProjectID uuid.UUID
	Kind      pgtype.Text
	NodeID    *uuid.UUID
	Direction string
}

type ListArchEdgesRow struct {
	ID            uuid.UUID
	ProjectID     uuid.UUID
	FromNodeID    uuid.UUID
	ToNodeID      uuid.UUID
	Kind          string
	Label         string
	DescriptionMd string
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
	FromSlug      string
	FromName      string
	ToSlug        string
	ToName        string
}

func (q *Queries) ListArchEdges(ctx context.Context, arg ListArchEdgesParams) ([]ListArchEdgesRow, error) {
	rows, err := q.db.Query(ctx, listArchEdges,
		arg.ProjectID,
		arg.Kind,
		arg.NodeID,
		arg.Direction,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListArchEdgesRow{}
	for rows.Next() {
		var i ListArchEdgesRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.FromNodeID,
			&i.ToNodeID,
			&i.Kind,
			&i.Label,
			&i.DescriptionMd,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.FromSlug,
			&i.FromName,
			&i.ToSlug,
			&i.ToName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listArchKinds = `-- name: ListArchKinds :many
SELECT project_id, key, label, icon, color, description, is_default, created_at
FROM arch_node_kinds
WHERE project_id = $1
ORDER BY is_default DESC, label
`

func (q *Queries) ListArchKinds(ctx context.Context, projectID uuid.UUID) ([]ArchNodeKind, error) {
	rows, err := q.db.Query(ctx, listArchKinds, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ArchNodeKind{}
	for rows.Next() {
		var i ArchNodeKind
		if err := rows.Scan(
			&i.ProjectID,
			&i.Key,
			&i.Label,
			&i.Icon,
			&i.Color,
			&i.Description,
			&i.IsDefault,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listArchNodeLinks = `-- name: ListArchNodeLinks :many
SELECT project_id, node_id, link_type, target_id, created_at
FROM arch_node_links WHERE node_id = $1
ORDER BY link_type, target_id
`

func (q *Queries) ListArchNodeLinks(ctx context.Context, nodeID uuid.UUID) ([]ArchNodeLink, error) {
	rows, err := q.db.Query(ctx, listArchNodeLinks, nodeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ArchNodeLink{}
	for rows.Next() {
		var i ArchNodeLink
		if err := rows.Scan(
			&i.ProjectID,
			&i.NodeID,
			&i.LinkType,
			&i.TargetID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listArchNodes = `-- name: ListArchNodes :many
SELECT n.id, n.project_id, n.slug, n.parent_id, n.kind, n.name, n.description_md,
       n.metadata, n.linked_repo, n.linked_path, n.position, n.created_at, n.updated_at
FROM arch_nodes n
WHERE n.project_id = $1::uuid
  AND ($2::text IS NULL OR n.parent_id = (
       SELECT p.id FROM arch_nodes p
       WHERE p.project_id = $1::uuid
         AND p.slug = $2::text))
  AND (NOT $3::bool OR n.parent_id IS NULL)
ORDER BY n.position, n.slug
`

type ListArchNodesParams struct {
	ProjectID  uuid.UUID
	ParentSlug pgtype.Text
	RootOnly   bool
}

type ListArchNodesRow struct {
	ID            uuid.UUID
	ProjectID     uuid.UUID
	Slug          string
	ParentID      *uuid.UUID
	Kind          string
	Name          string
	DescriptionMd string
	Metadata      []byte
	LinkedRepo    pgtype.Text
	LinkedPath    pgtype.Text
	Position      int32
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
}

func (q *Queries) ListArchNodes(ctx context.Context, arg ListArchNodesParams) ([]ListArchNodesRow, error) {
	rows, err := q.db.Query(ctx, listArchNodes, arg.ProjectID, arg.ParentSlug, arg.RootOnly)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListArchNodesRow{}
	for rows.Next() {
		var i ListArchNodesRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Slug,
			&i.ParentID,
			&i.Kind,
			&i.Name,
			&i.DescriptionMd,
			&i.Metadata,
			&i.LinkedRepo,
			&i.LinkedPath,
			&i.Position,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const moveArchNode = `-- name: MoveArchNode :one
UPDATE arch_nodes
SET parent_id = $1::uuid,
    updated_by_user_id = $2::uuid,
    updated_by_token_id = $3::uuid,
    updated_at = now()
WHERE id = $4::uuid
RETURNING id, project_id, slug, parent_id, kind, name, description_md,
          metadata, linked_repo, linked_path, position, created_at, updated_at
`

type MoveArchNodeParams struct {
	ParentID      *uuid.UUID
	AuthorUserID  *uuid.UUID
	AuthorTokenID *uuid.UUID
	ID            uuid.UUID
}

type MoveArchNodeRow struct {
	ID            uuid.UUID
	ProjectID     uuid.UUID
	Slug          string
	ParentID      *uuid.UUID
	Kind          string
	Name          string
	DescriptionMd string
	Metadata      []byte
	LinkedRepo    pgtype.Text
	LinkedPath    pgtype.Text
	Position      int32
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
}

func (q *Queries) MoveArchNode(ctx context.Context, arg MoveArchNodeParams) (MoveArchNodeRow, error) {
	row := q.db.QueryRow(ctx, moveArchNode,
		arg.ParentID,
		arg.AuthorUserID,
		arg.AuthorTokenID,
		arg.ID,
	)
	var i MoveArchNodeRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Slug,
		&i.ParentID,
		&i.Kind,
		&i.Name,
		&i.DescriptionMd,
		&i.Metadata,
		&i.LinkedRepo,
		&i.LinkedPath,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateArchNode = `-- name: UpdateArchNode :one
UPDATE arch_nodes
SET parent_id = $1::uuid,
    kind = $2::text,
    name = $3::text,
    description_md = $4::text,
    metadata = $5::jsonb,
    linked_repo = $6::text,
    linked_path = $7::text,
    position = $8::int,
    updated_by_user_id = $9::uuid,
    updated_by_token_id = $10::uuid,
    updated_at = now()
WHERE id = $11::uuid
RETURNING id, project_id, slug, parent_id, kind, name, description_md,
          metadata, linked_repo, linked_path, position,
          created_at, updated_at
`

type UpdateArchNodeParams struct {
	ParentID      *uuid.UUID
	Kind          string
	Name          string
	DescriptionMd string
	Metadata      []byte
	LinkedRepo    pgtype.Text
	LinkedPath    pgtype.Text
	Position      int32
	AuthorUserID  *uuid.UUID
	AuthorTokenID *uuid.UUID
	ID            uuid.UUID
}

type UpdateArchNodeRow struct {
	ID            uuid.UUID
	ProjectID     uuid.UUID
	Slug          string
	ParentID      *uuid.UUID
	Kind          string
	Name          string
	DescriptionMd string
	Metadata      []byte
	LinkedRepo    pgtype.Text
	LinkedPath    pgtype.Text
	Position      int32
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
}

func (q *Queries) UpdateArchNode(ctx context.Context, arg UpdateArchNodeParams) (UpdateArchNodeRow, error) {
	row := q.db.QueryRow(ctx, updateArchNode,
		arg.ParentID,
		arg.Kind,
		arg.Name,
		arg.DescriptionMd,
		arg.Metadata,
		arg.LinkedRepo,
		arg.LinkedPath,
		arg.Position,
		arg.AuthorUserID,
		arg.AuthorTokenID,
		arg.ID,
	)
	var i UpdateArchNodeRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Slug,
		&i.ParentID,
		&i.Kind,
		&i.Name,
		&i.DescriptionMd,
		&i.Metadata,
		&i.LinkedRepo,
		&i.LinkedPath,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertArchEdge = `-- name: UpsertArchEdge :one
INSERT INTO arch_edges (project_id, from_node_id, to_node_id, kind, label, description_md,
                        created_by_user_id, created_by_token_id,
                        updated_by_user_id, updated_by_token_id)
VALUES (
    $1::uuid,
    $2::uuid,
    $3::uuid,
    $4::text,
    $5::text,
    $6::text,
    $7::uuid,
    $8::uuid,
    $7::uuid,
    $8::uuid
)
ON CONFLICT (project_id, from_node_id, to_node_id, kind) DO UPDATE
SET label = EXCLUDED.label,
    description_md = EXCLUDED.description_md,
    updated_by_user_id = EXCLUDED.updated_by_user_id,
    updated_by_token_id = EXCLUDED.updated_by_token_id,
    updated_at = now()
RETURNING id, project_id, from_node_id, to_node_id, kind, label, description_md, created_at, updated_at
`

type UpsertArchEdgeParams struct {
	ProjectID     uuid.UUID
	FromNodeID    uuid.UUID
	ToNodeID      uuid.UUID
	Kind          string
	Label         string
	DescriptionMd string
	AuthorUserID  *uuid.UUID
	AuthorTokenID *uuid.UUID
}

type UpsertArchEdgeRow struct {
	ID            uuid.UUID
	ProjectID     uuid.UUID
	FromNodeID    uuid.UUID
	ToNodeID      uuid.UUID
	Kind          string
	Label         string
	DescriptionMd string
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
}

func (q *Queries) UpsertArchEdge(ctx context.Context, arg UpsertArchEdgeParams) (UpsertArchEdgeRow, error) {
	row := q.db.QueryRow(ctx, upsertArchEdge,
		arg.ProjectID,
		arg.FromNodeID,
		arg.ToNodeID,
		arg.Kind,
		arg.Label,
		arg.DescriptionMd,
		arg.AuthorUserID,
		arg.AuthorTokenID,
	)
	var i UpsertArchEdgeRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.FromNodeID,
		&i.ToNodeID,
		&i.Kind,
		&i.Label,
		&i.DescriptionMd,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertArchKind = `-- name: UpsertArchKind :one
INSERT INTO arch_node_kinds (project_id, key, label, icon, color, description, is_default)
VALUES ($1, $2, $3, $4, $5, $6, false)
ON CONFLICT (project_id, key) DO UPDATE
SET label = EXCLUDED.label,
    icon = EXCLUDED.icon,
    color = EXCLUDED.color,
    description = EXCLUDED.description
RETURNING project_id, key, label, icon, color, description, is_default, created_at
`

type UpsertArchKindParams struct {
	ProjectID   uuid.UUID
	Key         string
	Label       string
	Icon        string
	Color       string
	Description string
}

func (q *Queries) UpsertArchKind(ctx context.Context, arg UpsertArchKindParams) (ArchNodeKind, error) {
	row := q.db.QueryRow(ctx, upsertArchKind,
		arg.ProjectID,
		arg.Key,
		arg.Label,
		arg.Icon,
		arg.Color,
		arg.Description,
	)
	var i ArchNodeKind
	err := row.Scan(
		&i.ProjectID,
		&i.Key,
		&i.Label,
		&i.Icon,
		&i.Color,
		&i.Description,
		&i.IsDefault,
		&i.CreatedAt,
	)
	return i, err
}
