// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: arch_versioning.sql

package dbq

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const buildArchSnapshot = `-- name: BuildArchSnapshot :one
SELECT jsonb_build_object(
    'nodes', COALESCE((
        SELECT jsonb_agg(to_jsonb(n.*) ORDER BY n.position, n.created_at)
        FROM arch_nodes n
        WHERE n.project_id = $1::uuid
    ), '[]'::jsonb),
    'edges', COALESCE((
        SELECT jsonb_agg(to_jsonb(e.*) ORDER BY e.created_at)
        FROM arch_edges e
        WHERE e.project_id = $1::uuid
    ), '[]'::jsonb),
    'kinds', COALESCE((
        SELECT jsonb_agg(to_jsonb(k.*) ORDER BY k.key)
        FROM arch_node_kinds k
        WHERE k.project_id = $1::uuid
    ), '[]'::jsonb),
    'links', COALESCE((
        SELECT jsonb_agg(to_jsonb(l.*) ORDER BY l.created_at)
        FROM arch_node_links l
        WHERE l.project_id = $1::uuid
    ), '[]'::jsonb)
)::jsonb AS snapshot
`

// Build the full graph snapshot for one project as a single JSONB
// document. Used both by the migration baseline and by the runtime
// flush path.
func (q *Queries) BuildArchSnapshot(ctx context.Context, projectID uuid.UUID) ([]byte, error) {
	row := q.db.QueryRow(ctx, buildArchSnapshot, projectID)
	var snapshot []byte
	err := row.Scan(&snapshot)
	return snapshot, err
}

const deleteArchLock = `-- name: DeleteArchLock :exec
DELETE FROM arch_locks WHERE project_id = $1::uuid
`

func (q *Queries) DeleteArchLock(ctx context.Context, projectID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteArchLock, projectID)
	return err
}

const extendArchLock = `-- name: ExtendArchLock :exec
UPDATE arch_locks
SET last_write_at = now(),
    write_count = write_count + 1,
    author_token_id = $1::uuid
WHERE project_id = $2::uuid
`

type ExtendArchLockParams struct {
	AuthorTokenID *uuid.UUID
	ProjectID     uuid.UUID
}

func (q *Queries) ExtendArchLock(ctx context.Context, arg ExtendArchLockParams) error {
	_, err := q.db.Exec(ctx, extendArchLock, arg.AuthorTokenID, arg.ProjectID)
	return err
}

const getArchLock = `-- name: GetArchLock :one

SELECT project_id, author_user_id, author_token_id, locked_at,
       last_write_at, write_count, base_version
FROM arch_locks
WHERE project_id = $1::uuid
`

// Arch versioning: per-project editing sessions (locks) and their
// snapshot revisions. The lock is the singleton "open session" per
// project; revisions is the append-only log of closed sessions.
func (q *Queries) GetArchLock(ctx context.Context, projectID uuid.UUID) (ArchLock, error) {
	row := q.db.QueryRow(ctx, getArchLock, projectID)
	var i ArchLock
	err := row.Scan(
		&i.ProjectID,
		&i.AuthorUserID,
		&i.AuthorTokenID,
		&i.LockedAt,
		&i.LastWriteAt,
		&i.WriteCount,
		&i.BaseVersion,
	)
	return i, err
}

const getArchLockForUpdate = `-- name: GetArchLockForUpdate :one
SELECT project_id, author_user_id, author_token_id, locked_at,
       last_write_at, write_count, base_version
FROM arch_locks
WHERE project_id = $1::uuid
FOR UPDATE
`

// Same shape as GetArchLock but with FOR UPDATE; used inside a write
// transaction to atomically acquire/extend the lock.
func (q *Queries) GetArchLockForUpdate(ctx context.Context, projectID uuid.UUID) (ArchLock, error) {
	row := q.db.QueryRow(ctx, getArchLockForUpdate, projectID)
	var i ArchLock
	err := row.Scan(
		&i.ProjectID,
		&i.AuthorUserID,
		&i.AuthorTokenID,
		&i.LockedAt,
		&i.LastWriteAt,
		&i.WriteCount,
		&i.BaseVersion,
	)
	return i, err
}

const getArchRevision = `-- name: GetArchRevision :one
SELECT id, project_id, version, snapshot, message,
       author_user_id, author_token_id, write_count, auto_flushed, created_at
FROM arch_revisions
WHERE project_id = $1::uuid
  AND version = $2::int
`

type GetArchRevisionParams struct {
	ProjectID uuid.UUID
	Version   int32
}

func (q *Queries) GetArchRevision(ctx context.Context, arg GetArchRevisionParams) (ArchRevision, error) {
	row := q.db.QueryRow(ctx, getArchRevision, arg.ProjectID, arg.Version)
	var i ArchRevision
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Version,
		&i.Snapshot,
		&i.Message,
		&i.AuthorUserID,
		&i.AuthorTokenID,
		&i.WriteCount,
		&i.AutoFlushed,
		&i.CreatedAt,
	)
	return i, err
}

const getProjectArchIdleSeconds = `-- name: GetProjectArchIdleSeconds :one
SELECT arch_lock_idle_seconds FROM projects WHERE id = $1::uuid
`

// Returns the project's idle threshold (override or NULL).
func (q *Queries) GetProjectArchIdleSeconds(ctx context.Context, projectID uuid.UUID) (pgtype.Int4, error) {
	row := q.db.QueryRow(ctx, getProjectArchIdleSeconds, projectID)
	var arch_lock_idle_seconds pgtype.Int4
	err := row.Scan(&arch_lock_idle_seconds)
	return arch_lock_idle_seconds, err
}

const insertArchLock = `-- name: InsertArchLock :exec
INSERT INTO arch_locks (project_id, author_user_id, author_token_id,
                        locked_at, last_write_at, write_count, base_version)
VALUES (
    $1::uuid,
    $2::uuid,
    $3::uuid,
    now(), now(), 1,
    $4::int
)
`

type InsertArchLockParams struct {
	ProjectID     uuid.UUID
	AuthorUserID  uuid.UUID
	AuthorTokenID *uuid.UUID
	BaseVersion   int32
}

func (q *Queries) InsertArchLock(ctx context.Context, arg InsertArchLockParams) error {
	_, err := q.db.Exec(ctx, insertArchLock,
		arg.ProjectID,
		arg.AuthorUserID,
		arg.AuthorTokenID,
		arg.BaseVersion,
	)
	return err
}

const insertArchRevision = `-- name: InsertArchRevision :one
INSERT INTO arch_revisions (project_id, version, snapshot, message,
                            author_user_id, author_token_id,
                            write_count, auto_flushed)
VALUES (
    $1::uuid,
    $2::int,
    $3::jsonb,
    $4::text,
    $5::uuid,
    $6::uuid,
    $7::int,
    $8::bool
)
RETURNING id, version, created_at
`

type InsertArchRevisionParams struct {
	ProjectID     uuid.UUID
	Version       int32
	Snapshot      []byte
	Message       string
	AuthorUserID  *uuid.UUID
	AuthorTokenID *uuid.UUID
	WriteCount    int32
	AutoFlushed   bool
}

type InsertArchRevisionRow struct {
	ID        uuid.UUID
	Version   int32
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) InsertArchRevision(ctx context.Context, arg InsertArchRevisionParams) (InsertArchRevisionRow, error) {
	row := q.db.QueryRow(ctx, insertArchRevision,
		arg.ProjectID,
		arg.Version,
		arg.Snapshot,
		arg.Message,
		arg.AuthorUserID,
		arg.AuthorTokenID,
		arg.WriteCount,
		arg.AutoFlushed,
	)
	var i InsertArchRevisionRow
	err := row.Scan(&i.ID, &i.Version, &i.CreatedAt)
	return i, err
}

const listArchRevisions = `-- name: ListArchRevisions :many
SELECT id, version, message, author_user_id, author_token_id,
       write_count, auto_flushed, created_at
FROM arch_revisions
WHERE project_id = $1::uuid
  AND ($2::int IS NULL
       OR version < $2::int)
ORDER BY version DESC
LIMIT $3::int
`

type ListArchRevisionsParams struct {
	ProjectID     uuid.UUID
	BeforeVersion pgtype.Int4
	PageLimit     int32
}

type ListArchRevisionsRow struct {
	ID            uuid.UUID
	Version       int32
	Message       string
	AuthorUserID  *uuid.UUID
	AuthorTokenID *uuid.UUID
	WriteCount    int32
	AutoFlushed   bool
	CreatedAt     pgtype.Timestamptz
}

// History view: omits the (potentially large) snapshot column. Newest
// first. `before_version` lets the caller paginate; pass NULL to start
// from the top.
func (q *Queries) ListArchRevisions(ctx context.Context, arg ListArchRevisionsParams) ([]ListArchRevisionsRow, error) {
	rows, err := q.db.Query(ctx, listArchRevisions, arg.ProjectID, arg.BeforeVersion, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListArchRevisionsRow{}
	for rows.Next() {
		var i ListArchRevisionsRow
		if err := rows.Scan(
			&i.ID,
			&i.Version,
			&i.Message,
			&i.AuthorUserID,
			&i.AuthorTokenID,
			&i.WriteCount,
			&i.AutoFlushed,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExpiredArchLocks = `-- name: ListExpiredArchLocks :many
SELECT l.project_id, l.author_user_id, l.author_token_id,
       l.locked_at, l.last_write_at, l.write_count, l.base_version,
       COALESCE(p.arch_lock_idle_seconds, $1::int) AS idle_seconds
FROM arch_locks l
JOIN projects p ON p.id = l.project_id
WHERE now() - l.last_write_at
      > make_interval(secs => COALESCE(p.arch_lock_idle_seconds, $1::int))
`

type ListExpiredArchLocksRow struct {
	ProjectID     uuid.UUID
	AuthorUserID  uuid.UUID
	AuthorTokenID *uuid.UUID
	LockedAt      pgtype.Timestamptz
	LastWriteAt   pgtype.Timestamptz
	WriteCount    int32
	BaseVersion   int32
	IdleSeconds   pgtype.Int4
}

// Returns all locks whose last write is older than the project's idle
// threshold. The threshold is (projects.arch_lock_idle_seconds OR the
// caller-supplied default). Used by the background ticker.
func (q *Queries) ListExpiredArchLocks(ctx context.Context, defaultIdleSeconds int32) ([]ListExpiredArchLocksRow, error) {
	rows, err := q.db.Query(ctx, listExpiredArchLocks, defaultIdleSeconds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListExpiredArchLocksRow{}
	for rows.Next() {
		var i ListExpiredArchLocksRow
		if err := rows.Scan(
			&i.ProjectID,
			&i.AuthorUserID,
			&i.AuthorTokenID,
			&i.LockedAt,
			&i.LastWriteAt,
			&i.WriteCount,
			&i.BaseVersion,
			&i.IdleSeconds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const maxArchRevisionVersion = `-- name: MaxArchRevisionVersion :one
SELECT COALESCE(MAX(version), 0)::int AS version
FROM arch_revisions
WHERE project_id = $1::uuid
`

// Returns the highest existing version for the project, or 0 when the
// project has no revisions yet. Used to compute the next version on
// both lock acquisition (base_version) and snapshot insertion.
func (q *Queries) MaxArchRevisionVersion(ctx context.Context, projectID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, maxArchRevisionVersion, projectID)
	var version int32
	err := row.Scan(&version)
	return version, err
}
