// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: cycles.sql

package dbq

import (
	"context"

	"github.com/google/uuid"
)

const acquireCycleLock = `-- name: AcquireCycleLock :exec
SELECT pg_advisory_xact_lock(
    hashtext('cycles'), hashtext($1::text)
)
`

func (q *Queries) AcquireCycleLock(ctx context.Context, projectID string) error {
	_, err := q.db.Exec(ctx, acquireCycleLock, projectID)
	return err
}

const closeCycle = `-- name: CloseCycle :exec
UPDATE cycles
SET closed_at = now(),
    closed_by_user_id = $1::uuid,
    closed_by_token_id = $2::uuid
WHERE id = $3::uuid
`

type CloseCycleParams struct {
	ClosedByUserID  *uuid.UUID
	ClosedByTokenID *uuid.UUID
	ID              uuid.UUID
}

func (q *Queries) CloseCycle(ctx context.Context, arg CloseCycleParams) error {
	_, err := q.db.Exec(ctx, closeCycle, arg.ClosedByUserID, arg.ClosedByTokenID, arg.ID)
	return err
}

const getActiveCycle = `-- name: GetActiveCycle :one
SELECT id, project_id, name, position, opened_at, closed_at,
       closed_by_user_id, closed_by_token_id
FROM cycles WHERE project_id = $1 AND closed_at IS NULL
`

func (q *Queries) GetActiveCycle(ctx context.Context, projectID uuid.UUID) (Cycle, error) {
	row := q.db.QueryRow(ctx, getActiveCycle, projectID)
	var i Cycle
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Position,
		&i.OpenedAt,
		&i.ClosedAt,
		&i.ClosedByUserID,
		&i.ClosedByTokenID,
	)
	return i, err
}

const getCycle = `-- name: GetCycle :one
SELECT id, project_id, name, position, opened_at, closed_at,
       closed_by_user_id, closed_by_token_id
FROM cycles WHERE id = $1
`

func (q *Queries) GetCycle(ctx context.Context, id uuid.UUID) (Cycle, error) {
	row := q.db.QueryRow(ctx, getCycle, id)
	var i Cycle
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Position,
		&i.OpenedAt,
		&i.ClosedAt,
		&i.ClosedByUserID,
		&i.ClosedByTokenID,
	)
	return i, err
}

const getProjectCycleLabel = `-- name: GetProjectCycleLabel :one
SELECT cycle_label FROM projects WHERE id = $1
`

func (q *Queries) GetProjectCycleLabel(ctx context.Context, id uuid.UUID) (string, error) {
	row := q.db.QueryRow(ctx, getProjectCycleLabel, id)
	var cycle_label string
	err := row.Scan(&cycle_label)
	return cycle_label, err
}

const insertCycle = `-- name: InsertCycle :one
INSERT INTO cycles (project_id, name, position)
VALUES ($1::uuid,
        $2::text,
        $3::int)
RETURNING id, project_id, name, position, opened_at, closed_at,
          closed_by_user_id, closed_by_token_id
`

type InsertCycleParams struct {
	ProjectID uuid.UUID
	Name      string
	Position  int32
}

func (q *Queries) InsertCycle(ctx context.Context, arg InsertCycleParams) (Cycle, error) {
	row := q.db.QueryRow(ctx, insertCycle, arg.ProjectID, arg.Name, arg.Position)
	var i Cycle
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Position,
		&i.OpenedAt,
		&i.ClosedAt,
		&i.ClosedByUserID,
		&i.ClosedByTokenID,
	)
	return i, err
}

const listCycles = `-- name: ListCycles :many
SELECT id, project_id, name, position, opened_at, closed_at,
       closed_by_user_id, closed_by_token_id
FROM cycles
WHERE project_id = $1
ORDER BY position DESC
`

func (q *Queries) ListCycles(ctx context.Context, projectID uuid.UUID) ([]Cycle, error) {
	rows, err := q.db.Query(ctx, listCycles, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Cycle{}
	for rows.Next() {
		var i Cycle
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.Position,
			&i.OpenedAt,
			&i.ClosedAt,
			&i.ClosedByUserID,
			&i.ClosedByTokenID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockActiveCycle = `-- name: LockActiveCycle :one
SELECT id, project_id, name, position, opened_at, closed_at,
       closed_by_user_id, closed_by_token_id
FROM cycles WHERE project_id = $1 AND closed_at IS NULL
FOR UPDATE
`

func (q *Queries) LockActiveCycle(ctx context.Context, projectID uuid.UUID) (Cycle, error) {
	row := q.db.QueryRow(ctx, lockActiveCycle, projectID)
	var i Cycle
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Position,
		&i.OpenedAt,
		&i.ClosedAt,
		&i.ClosedByUserID,
		&i.ClosedByTokenID,
	)
	return i, err
}

const movePartialFeatureSubtrees = `-- name: MovePartialFeatureSubtrees :execrows
WITH RECURSIVE partial_features AS (
    SELECT id FROM tasks
    WHERE cycle_id = $2::uuid
      AND type = 'feature'
      AND state NOT IN ('done', 'wont_do')
), subtree AS (
    SELECT id FROM partial_features
    UNION
    SELECT t.id FROM tasks t
    INNER JOIN subtree s ON t.parent_task_id = s.id
)
UPDATE tasks SET cycle_id = $1::uuid
WHERE id IN (SELECT id FROM subtree)
`

type MovePartialFeatureSubtreesParams struct {
	ToCycle   uuid.UUID
	FromCycle uuid.UUID
}

// For every feature in `from_cycle` that isn't done, move it AND
// all its recursive descendants to `to_cycle`. Done children of
// those features get re-stamped (they had cycle_id = from_cycle).
func (q *Queries) MovePartialFeatureSubtrees(ctx context.Context, arg MovePartialFeatureSubtreesParams) (int64, error) {
	result, err := q.db.Exec(ctx, movePartialFeatureSubtrees, arg.ToCycle, arg.FromCycle)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const moveStandaloneNonDone = `-- name: MoveStandaloneNonDone :execrows
UPDATE tasks SET cycle_id = $1::uuid
WHERE cycle_id = $2::uuid
  AND state NOT IN ('done', 'wont_do')
`

type MoveStandaloneNonDoneParams struct {
	ToCycle   uuid.UUID
	FromCycle uuid.UUID
}

// Move any task in `from_cycle` that is not yet done AND was not
// already moved as part of a feature subtree (i.e. its cycle_id is
// still the closing cycle).
func (q *Queries) MoveStandaloneNonDone(ctx context.Context, arg MoveStandaloneNonDoneParams) (int64, error) {
	result, err := q.db.Exec(ctx, moveStandaloneNonDone, arg.ToCycle, arg.FromCycle)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const nextCyclePosition = `-- name: NextCyclePosition :one
SELECT COALESCE(MAX(position), 0) + 1 FROM cycles WHERE project_id = $1
`

func (q *Queries) NextCyclePosition(ctx context.Context, projectID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, nextCyclePosition, projectID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}
