// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: dependencies.sql

package dbq

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const acquireDepLock = `-- name: AcquireDepLock :exec
SELECT pg_advisory_xact_lock($1::int, hashtext($2::text))
`

type AcquireDepLockParams struct {
	Namespace int32
	ProjectID string
}

func (q *Queries) AcquireDepLock(ctx context.Context, arg AcquireDepLockParams) error {
	_, err := q.db.Exec(ctx, acquireDepLock, arg.Namespace, arg.ProjectID)
	return err
}

const insertDependency = `-- name: InsertDependency :execrows
INSERT INTO task_dependencies (task_id, depends_on_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type InsertDependencyParams struct {
	TaskID      uuid.UUID
	DependsOnID uuid.UUID
}

func (q *Queries) InsertDependency(ctx context.Context, arg InsertDependencyParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertDependency, arg.TaskID, arg.DependsOnID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listDependents = `-- name: ListDependents :many
SELECT task_id FROM task_dependencies WHERE depends_on_id = $1
`

func (q *Queries) ListDependents(ctx context.Context, dependsOnID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listDependents, dependsOnID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var task_id uuid.UUID
		if err := rows.Scan(&task_id); err != nil {
			return nil, err
		}
		items = append(items, task_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDependsOn = `-- name: ListDependsOn :many
SELECT depends_on_id FROM task_dependencies WHERE task_id = $1
`

func (q *Queries) ListDependsOn(ctx context.Context, taskID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listDependsOn, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var depends_on_id uuid.UUID
		if err := rows.Scan(&depends_on_id); err != nil {
			return nil, err
		}
		items = append(items, depends_on_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDoneDependentsInconsistencies = `-- name: ListDoneDependentsInconsistencies :many
SELECT t.id AS task_id,
       ARRAY_AGG(d.id ORDER BY d.id)::uuid[] AS done_dependent_ids
FROM tasks t
JOIN task_dependencies td ON td.depends_on_id = t.id
JOIN tasks d ON d.id = td.task_id
WHERE t.project_id = $1
  AND t.state <> 'done'
  AND d.state = 'done'
GROUP BY t.id
ORDER BY t.id
`

type ListDoneDependentsInconsistenciesRow struct {
	TaskID           uuid.UUID
	DoneDependentIds []uuid.UUID
}

func (q *Queries) ListDoneDependentsInconsistencies(ctx context.Context, projectID uuid.UUID) ([]ListDoneDependentsInconsistenciesRow, error) {
	rows, err := q.db.Query(ctx, listDoneDependentsInconsistencies, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDoneDependentsInconsistenciesRow{}
	for rows.Next() {
		var i ListDoneDependentsInconsistenciesRow
		if err := rows.Scan(&i.TaskID, &i.DoneDependentIds); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectDependencies = `-- name: ListProjectDependencies :many
SELECT d.task_id, d.depends_on_id
FROM task_dependencies d
JOIN tasks t ON t.id = d.task_id
WHERE t.project_id = $1
`

func (q *Queries) ListProjectDependencies(ctx context.Context, projectID uuid.UUID) ([]TaskDependency, error) {
	rows, err := q.db.Query(ctx, listProjectDependencies, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TaskDependency{}
	for rows.Next() {
		var i TaskDependency
		if err := rows.Scan(&i.TaskID, &i.DependsOnID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockTaskRow = `-- name: LockTaskRow :exec
SELECT id FROM tasks WHERE id = $1 FOR UPDATE
`

func (q *Queries) LockTaskRow(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, lockTaskRow, id)
	return err
}

const lockTwoTaskRows = `-- name: LockTwoTaskRows :many
SELECT id FROM tasks
WHERE id = ANY($1::uuid[])
ORDER BY id
FOR UPDATE
`

func (q *Queries) LockTwoTaskRows(ctx context.Context, ids []uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, lockTwoTaskRows, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const projectIDForTask = `-- name: ProjectIDForTask :one
SELECT project_id FROM tasks WHERE id = $1
`

func (q *Queries) ProjectIDForTask(ctx context.Context, id uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, projectIDForTask, id)
	var project_id uuid.UUID
	err := row.Scan(&project_id)
	return project_id, err
}

const removeDependency = `-- name: RemoveDependency :execrows
DELETE FROM task_dependencies WHERE task_id = $1 AND depends_on_id = $2
`

type RemoveDependencyParams struct {
	TaskID      uuid.UUID
	DependsOnID uuid.UUID
}

func (q *Queries) RemoveDependency(ctx context.Context, arg RemoveDependencyParams) (int64, error) {
	result, err := q.db.Exec(ctx, removeDependency, arg.TaskID, arg.DependsOnID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const wouldCreateCycle = `-- name: WouldCreateCycle :one
WITH RECURSIVE reachable AS (
  SELECT depends_on_id AS rid FROM task_dependencies WHERE task_id = $2::uuid
  UNION
  SELECT d.depends_on_id AS rid
  FROM task_dependencies d
  JOIN reachable r ON r.rid = d.task_id
)
SELECT (EXISTS (SELECT 1 FROM reachable WHERE rid = $1::uuid)
        OR $2::uuid = $1::uuid) AS hit
`

type WouldCreateCycleParams struct {
	Target uuid.UUID
	Start  uuid.UUID
}

func (q *Queries) WouldCreateCycle(ctx context.Context, arg WouldCreateCycleParams) (pgtype.Bool, error) {
	row := q.db.QueryRow(ctx, wouldCreateCycle, arg.Target, arg.Start)
	var hit pgtype.Bool
	err := row.Scan(&hit)
	return hit, err
}
