// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: docs.sql

package dbq

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getDocumentByPath = `-- name: GetDocumentByPath :one
SELECT id, current_version
FROM documents
WHERE scope = $1::text
  AND project_id IS NOT DISTINCT FROM $2::uuid
  AND path = $3::text
`

type GetDocumentByPathParams struct {
	Scope     string
	ProjectID *uuid.UUID
	Path      string
}

type GetDocumentByPathRow struct {
	ID             uuid.UUID
	CurrentVersion int32
}

func (q *Queries) GetDocumentByPath(ctx context.Context, arg GetDocumentByPathParams) (GetDocumentByPathRow, error) {
	row := q.db.QueryRow(ctx, getDocumentByPath, arg.Scope, arg.ProjectID, arg.Path)
	var i GetDocumentByPathRow
	err := row.Scan(&i.ID, &i.CurrentVersion)
	return i, err
}

const getDocumentForDelete = `-- name: GetDocumentForDelete :one
SELECT id, current_version, title, description, content_md, frontmatter
FROM documents
WHERE scope = $1::text
  AND project_id IS NOT DISTINCT FROM $2::uuid
  AND path = $3::text
  AND deleted_at IS NULL
`

type GetDocumentForDeleteParams struct {
	Scope     string
	ProjectID *uuid.UUID
	Path      string
}

type GetDocumentForDeleteRow struct {
	ID             uuid.UUID
	CurrentVersion int32
	Title          string
	Description    string
	ContentMd      string
	Frontmatter    []byte
}

func (q *Queries) GetDocumentForDelete(ctx context.Context, arg GetDocumentForDeleteParams) (GetDocumentForDeleteRow, error) {
	row := q.db.QueryRow(ctx, getDocumentForDelete, arg.Scope, arg.ProjectID, arg.Path)
	var i GetDocumentForDeleteRow
	err := row.Scan(
		&i.ID,
		&i.CurrentVersion,
		&i.Title,
		&i.Description,
		&i.ContentMd,
		&i.Frontmatter,
	)
	return i, err
}

const getDocumentVersion = `-- name: GetDocumentVersion :one
SELECT id, document_id, version, title, description, content_md, frontmatter,
       message, author_user_id, author_token_id, created_at
FROM document_versions
WHERE document_id = $1 AND version = $2
`

type GetDocumentVersionParams struct {
	DocumentID uuid.UUID
	Version    int32
}

func (q *Queries) GetDocumentVersion(ctx context.Context, arg GetDocumentVersionParams) (DocumentVersion, error) {
	row := q.db.QueryRow(ctx, getDocumentVersion, arg.DocumentID, arg.Version)
	var i DocumentVersion
	err := row.Scan(
		&i.ID,
		&i.DocumentID,
		&i.Version,
		&i.Title,
		&i.Description,
		&i.ContentMd,
		&i.Frontmatter,
		&i.Message,
		&i.AuthorUserID,
		&i.AuthorTokenID,
		&i.CreatedAt,
	)
	return i, err
}

const insertDocument = `-- name: InsertDocument :one
INSERT INTO documents (
    scope, project_id, path, kind, title, description, content_md, frontmatter,
    current_version, created_by_user_id, created_by_token_id,
    updated_by_user_id, updated_by_token_id
)
VALUES (
    $1::text,
    $2::uuid,
    $3::text,
    $4::text,
    $5::text,
    $6::text,
    $7::text,
    $8::jsonb,
    1,
    $9::uuid,
    $10::uuid,
    $9::uuid,
    $10::uuid
)
RETURNING id, scope, project_id, path, kind, title, description, content_md,
          frontmatter, current_version, deleted_at,
          created_by_user_id, created_by_token_id,
          updated_by_user_id, updated_by_token_id,
          created_at, updated_at
`

type InsertDocumentParams struct {
	Scope            string
	ProjectID        *uuid.UUID
	Path             string
	Kind             string
	Title            string
	Description      string
	ContentMd        string
	Frontmatter      []byte
	CreatedByUserID  *uuid.UUID
	CreatedByTokenID *uuid.UUID
}

type InsertDocumentRow struct {
	ID               uuid.UUID
	Scope            string
	ProjectID        *uuid.UUID
	Path             string
	Kind             string
	Title            string
	Description      string
	ContentMd        string
	Frontmatter      []byte
	CurrentVersion   int32
	DeletedAt        pgtype.Timestamptz
	CreatedByUserID  *uuid.UUID
	CreatedByTokenID *uuid.UUID
	UpdatedByUserID  *uuid.UUID
	UpdatedByTokenID *uuid.UUID
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}

func (q *Queries) InsertDocument(ctx context.Context, arg InsertDocumentParams) (InsertDocumentRow, error) {
	row := q.db.QueryRow(ctx, insertDocument,
		arg.Scope,
		arg.ProjectID,
		arg.Path,
		arg.Kind,
		arg.Title,
		arg.Description,
		arg.ContentMd,
		arg.Frontmatter,
		arg.CreatedByUserID,
		arg.CreatedByTokenID,
	)
	var i InsertDocumentRow
	err := row.Scan(
		&i.ID,
		&i.Scope,
		&i.ProjectID,
		&i.Path,
		&i.Kind,
		&i.Title,
		&i.Description,
		&i.ContentMd,
		&i.Frontmatter,
		&i.CurrentVersion,
		&i.DeletedAt,
		&i.CreatedByUserID,
		&i.CreatedByTokenID,
		&i.UpdatedByUserID,
		&i.UpdatedByTokenID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertDocumentVersion = `-- name: InsertDocumentVersion :exec
INSERT INTO document_versions (
    document_id, version, title, description, content_md, frontmatter,
    message, author_user_id, author_token_id
)
VALUES (
    $1::uuid,
    $2::int,
    $3::text,
    $4::text,
    $5::text,
    $6::jsonb,
    $7::text,
    $8::uuid,
    $9::uuid
)
`

type InsertDocumentVersionParams struct {
	DocumentID    uuid.UUID
	Version       int32
	Title         string
	Description   string
	ContentMd     string
	Frontmatter   []byte
	Message       string
	AuthorUserID  *uuid.UUID
	AuthorTokenID *uuid.UUID
}

func (q *Queries) InsertDocumentVersion(ctx context.Context, arg InsertDocumentVersionParams) error {
	_, err := q.db.Exec(ctx, insertDocumentVersion,
		arg.DocumentID,
		arg.Version,
		arg.Title,
		arg.Description,
		arg.ContentMd,
		arg.Frontmatter,
		arg.Message,
		arg.AuthorUserID,
		arg.AuthorTokenID,
	)
	return err
}

const listDocumentVersions = `-- name: ListDocumentVersions :many
SELECT version, title, message, author_user_id, author_token_id, created_at
FROM document_versions
WHERE document_id = $1
ORDER BY version DESC
`

type ListDocumentVersionsRow struct {
	Version       int32
	Title         string
	Message       string
	AuthorUserID  *uuid.UUID
	AuthorTokenID *uuid.UUID
	CreatedAt     pgtype.Timestamptz
}

func (q *Queries) ListDocumentVersions(ctx context.Context, documentID uuid.UUID) ([]ListDocumentVersionsRow, error) {
	rows, err := q.db.Query(ctx, listDocumentVersions, documentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDocumentVersionsRow{}
	for rows.Next() {
		var i ListDocumentVersionsRow
		if err := rows.Scan(
			&i.Version,
			&i.Title,
			&i.Message,
			&i.AuthorUserID,
			&i.AuthorTokenID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDocuments = `-- name: ListDocuments :many
SELECT id, scope, project_id, path, kind, title, description, current_version,
       updated_by_user_id, updated_by_token_id, updated_at
FROM documents
WHERE scope = $1::text
  AND project_id IS NOT DISTINCT FROM $2::uuid
  AND deleted_at IS NULL
  AND ($3::text IS NULL OR path LIKE $3::text)
  AND ($4::text IS NULL OR kind = $4::text)
ORDER BY path
`

type ListDocumentsParams struct {
	Scope      string
	ProjectID  *uuid.UUID
	PathPrefix pgtype.Text
	Kind       pgtype.Text
}

type ListDocumentsRow struct {
	ID               uuid.UUID
	Scope            string
	ProjectID        *uuid.UUID
	Path             string
	Kind             string
	Title            string
	Description      string
	CurrentVersion   int32
	UpdatedByUserID  *uuid.UUID
	UpdatedByTokenID *uuid.UUID
	UpdatedAt        pgtype.Timestamptz
}

func (q *Queries) ListDocuments(ctx context.Context, arg ListDocumentsParams) ([]ListDocumentsRow, error) {
	rows, err := q.db.Query(ctx, listDocuments,
		arg.Scope,
		arg.ProjectID,
		arg.PathPrefix,
		arg.Kind,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDocumentsRow{}
	for rows.Next() {
		var i ListDocumentsRow
		if err := rows.Scan(
			&i.ID,
			&i.Scope,
			&i.ProjectID,
			&i.Path,
			&i.Kind,
			&i.Title,
			&i.Description,
			&i.CurrentVersion,
			&i.UpdatedByUserID,
			&i.UpdatedByTokenID,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const readDocument = `-- name: ReadDocument :one
SELECT id, scope, project_id, path, kind, title, description, content_md,
       frontmatter, current_version, deleted_at,
       created_by_user_id, created_by_token_id,
       updated_by_user_id, updated_by_token_id,
       created_at, updated_at
FROM documents
WHERE scope = $1::text
  AND project_id IS NOT DISTINCT FROM $2::uuid
  AND path = $3::text
  AND deleted_at IS NULL
`

type ReadDocumentParams struct {
	Scope     string
	ProjectID *uuid.UUID
	Path      string
}

type ReadDocumentRow struct {
	ID               uuid.UUID
	Scope            string
	ProjectID        *uuid.UUID
	Path             string
	Kind             string
	Title            string
	Description      string
	ContentMd        string
	Frontmatter      []byte
	CurrentVersion   int32
	DeletedAt        pgtype.Timestamptz
	CreatedByUserID  *uuid.UUID
	CreatedByTokenID *uuid.UUID
	UpdatedByUserID  *uuid.UUID
	UpdatedByTokenID *uuid.UUID
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}

func (q *Queries) ReadDocument(ctx context.Context, arg ReadDocumentParams) (ReadDocumentRow, error) {
	row := q.db.QueryRow(ctx, readDocument, arg.Scope, arg.ProjectID, arg.Path)
	var i ReadDocumentRow
	err := row.Scan(
		&i.ID,
		&i.Scope,
		&i.ProjectID,
		&i.Path,
		&i.Kind,
		&i.Title,
		&i.Description,
		&i.ContentMd,
		&i.Frontmatter,
		&i.CurrentVersion,
		&i.DeletedAt,
		&i.CreatedByUserID,
		&i.CreatedByTokenID,
		&i.UpdatedByUserID,
		&i.UpdatedByTokenID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const searchDocuments = `-- name: SearchDocuments :many
SELECT id, scope, project_id, path, kind, title, description, current_version,
       updated_by_user_id, updated_by_token_id, updated_at,
       ts_rank(search_vector, plainto_tsquery('simple', $1::text))::real AS rank
FROM documents
WHERE scope = $2::text
  AND project_id IS NOT DISTINCT FROM $3::uuid
  AND deleted_at IS NULL
  AND search_vector @@ plainto_tsquery('simple', $1::text)
  AND ($4::text IS NULL OR kind = $4::text)
ORDER BY rank DESC, path
`

type SearchDocumentsParams struct {
	Query     string
	Scope     string
	ProjectID *uuid.UUID
	Kind      pgtype.Text
}

type SearchDocumentsRow struct {
	ID               uuid.UUID
	Scope            string
	ProjectID        *uuid.UUID
	Path             string
	Kind             string
	Title            string
	Description      string
	CurrentVersion   int32
	UpdatedByUserID  *uuid.UUID
	UpdatedByTokenID *uuid.UUID
	UpdatedAt        pgtype.Timestamptz
	Rank             float32
}

func (q *Queries) SearchDocuments(ctx context.Context, arg SearchDocumentsParams) ([]SearchDocumentsRow, error) {
	rows, err := q.db.Query(ctx, searchDocuments,
		arg.Query,
		arg.Scope,
		arg.ProjectID,
		arg.Kind,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchDocumentsRow{}
	for rows.Next() {
		var i SearchDocumentsRow
		if err := rows.Scan(
			&i.ID,
			&i.Scope,
			&i.ProjectID,
			&i.Path,
			&i.Kind,
			&i.Title,
			&i.Description,
			&i.CurrentVersion,
			&i.UpdatedByUserID,
			&i.UpdatedByTokenID,
			&i.UpdatedAt,
			&i.Rank,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteDocument = `-- name: SoftDeleteDocument :exec
UPDATE documents
SET deleted_at = now(),
    current_version = $1::int,
    updated_by_user_id = $2::uuid,
    updated_by_token_id = $3::uuid
WHERE id = $4::uuid
`

type SoftDeleteDocumentParams struct {
	CurrentVersion   int32
	UpdatedByUserID  *uuid.UUID
	UpdatedByTokenID *uuid.UUID
	ID               uuid.UUID
}

func (q *Queries) SoftDeleteDocument(ctx context.Context, arg SoftDeleteDocumentParams) error {
	_, err := q.db.Exec(ctx, softDeleteDocument,
		arg.CurrentVersion,
		arg.UpdatedByUserID,
		arg.UpdatedByTokenID,
		arg.ID,
	)
	return err
}

const updateDocument = `-- name: UpdateDocument :one
UPDATE documents
SET kind = $1::text,
    title = $2::text,
    description = $3::text,
    content_md = $4::text,
    frontmatter = $5::jsonb,
    current_version = $6::int,
    updated_by_user_id = $7::uuid,
    updated_by_token_id = $8::uuid,
    deleted_at = NULL
WHERE id = $9::uuid
RETURNING id, scope, project_id, path, kind, title, description, content_md,
          frontmatter, current_version, deleted_at,
          created_by_user_id, created_by_token_id,
          updated_by_user_id, updated_by_token_id,
          created_at, updated_at
`

type UpdateDocumentParams struct {
	Kind             string
	Title            string
	Description      string
	ContentMd        string
	Frontmatter      []byte
	CurrentVersion   int32
	UpdatedByUserID  *uuid.UUID
	UpdatedByTokenID *uuid.UUID
	ID               uuid.UUID
}

type UpdateDocumentRow struct {
	ID               uuid.UUID
	Scope            string
	ProjectID        *uuid.UUID
	Path             string
	Kind             string
	Title            string
	Description      string
	ContentMd        string
	Frontmatter      []byte
	CurrentVersion   int32
	DeletedAt        pgtype.Timestamptz
	CreatedByUserID  *uuid.UUID
	CreatedByTokenID *uuid.UUID
	UpdatedByUserID  *uuid.UUID
	UpdatedByTokenID *uuid.UUID
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}

func (q *Queries) UpdateDocument(ctx context.Context, arg UpdateDocumentParams) (UpdateDocumentRow, error) {
	row := q.db.QueryRow(ctx, updateDocument,
		arg.Kind,
		arg.Title,
		arg.Description,
		arg.ContentMd,
		arg.Frontmatter,
		arg.CurrentVersion,
		arg.UpdatedByUserID,
		arg.UpdatedByTokenID,
		arg.ID,
	)
	var i UpdateDocumentRow
	err := row.Scan(
		&i.ID,
		&i.Scope,
		&i.ProjectID,
		&i.Path,
		&i.Kind,
		&i.Title,
		&i.Description,
		&i.ContentMd,
		&i.Frontmatter,
		&i.CurrentVersion,
		&i.DeletedAt,
		&i.CreatedByUserID,
		&i.CreatedByTokenID,
		&i.UpdatedByUserID,
		&i.UpdatedByTokenID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
