// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: markdown.sql

package dbq

import (
	"context"

	"github.com/google/uuid"
)

const getArchChipBySlug = `-- name: GetArchChipBySlug :one
SELECT id, name
FROM arch_nodes
WHERE project_id = $1::uuid
  AND slug = $2::text
`

type GetArchChipBySlugParams struct {
	ProjectID uuid.UUID
	Slug      string
}

type GetArchChipBySlugRow struct {
	ID   uuid.UUID
	Name string
}

// Resolves an architecture node chip by slug.
func (q *Queries) GetArchChipBySlug(ctx context.Context, arg GetArchChipBySlugParams) (GetArchChipBySlugRow, error) {
	row := q.db.QueryRow(ctx, getArchChipBySlug, arg.ProjectID, arg.Slug)
	var i GetArchChipBySlugRow
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const getDocChipByPath = `-- name: GetDocChipByPath :one
SELECT id, title
FROM documents
WHERE scope = 'project'
  AND project_id = $1::uuid
  AND path = $2::text
  AND deleted_at IS NULL
`

type GetDocChipByPathParams struct {
	ProjectID uuid.UUID
	Path      string
}

type GetDocChipByPathRow struct {
	ID    uuid.UUID
	Title string
}

// Resolves a doc chip by its logical path within a project.
func (q *Queries) GetDocChipByPath(ctx context.Context, arg GetDocChipByPathParams) (GetDocChipByPathRow, error) {
	row := q.db.QueryRow(ctx, getDocChipByPath, arg.ProjectID, arg.Path)
	var i GetDocChipByPathRow
	err := row.Scan(&i.ID, &i.Title)
	return i, err
}

const getTaskChipByShortID = `-- name: GetTaskChipByShortID :one

SELECT id, title, state
FROM tasks
WHERE project_id = $1::uuid
  AND id::text LIKE $2::text
LIMIT 1
`

type GetTaskChipByShortIDParams struct {
	ProjectID uuid.UUID
	Prefix    string
}

type GetTaskChipByShortIDRow struct {
	ID    uuid.UUID
	Title string
	State string
}

// Queries used by the markdown renderer to resolve cross-domain chip
// references ([[task:N]], [[doc:path]], [[arch:slug]]) into the
// target's current title for inline display.
// Resolves a task chip by the 8-char (or longer) UUID prefix the user
// typed. We match prefix with LIKE on the text form of the UUID. The
// query is scoped to a single project to keep the result deterministic
// when the same prefix matches across projects.
func (q *Queries) GetTaskChipByShortID(ctx context.Context, arg GetTaskChipByShortIDParams) (GetTaskChipByShortIDRow, error) {
	row := q.db.QueryRow(ctx, getTaskChipByShortID, arg.ProjectID, arg.Prefix)
	var i GetTaskChipByShortIDRow
	err := row.Scan(&i.ID, &i.Title, &i.State)
	return i, err
}
