// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: memberships.sql

package dbq

import (
	"context"

	"github.com/google/uuid"
)

const deleteMembership = `-- name: DeleteMembership :exec
DELETE FROM memberships
WHERE user_id = $1 AND project_id = $2 AND role_id = $3
`

type DeleteMembershipParams struct {
	UserID    uuid.UUID
	ProjectID uuid.UUID
	RoleID    uuid.UUID
}

func (q *Queries) DeleteMembership(ctx context.Context, arg DeleteMembershipParams) error {
	_, err := q.db.Exec(ctx, deleteMembership, arg.UserID, arg.ProjectID, arg.RoleID)
	return err
}

const insertMembership = `-- name: InsertMembership :exec
INSERT INTO memberships (user_id, project_id, role_id)
VALUES ($1, $2, $3)
ON CONFLICT DO NOTHING
`

type InsertMembershipParams struct {
	UserID    uuid.UUID
	ProjectID uuid.UUID
	RoleID    uuid.UUID
}

func (q *Queries) InsertMembership(ctx context.Context, arg InsertMembershipParams) error {
	_, err := q.db.Exec(ctx, insertMembership, arg.UserID, arg.ProjectID, arg.RoleID)
	return err
}

const listMembershipsForUser = `-- name: ListMembershipsForUser :many
SELECT p.id AS project_id, p.slug AS project_slug, p.name AS project_name,
       r.id AS role_id, r.key AS role_key, r.label AS role_label,
       COALESCE(r.color, '')::text AS role_color, r.position AS role_position
FROM memberships m
JOIN projects p ON p.id = m.project_id
JOIN roles    r ON r.id = m.role_id
WHERE m.user_id = $1
ORDER BY p.slug, r.position, r.label
`

type ListMembershipsForUserRow struct {
	ProjectID    uuid.UUID
	ProjectSlug  string
	ProjectName  string
	RoleID       uuid.UUID
	RoleKey      string
	RoleLabel    string
	RoleColor    string
	RolePosition int32
}

func (q *Queries) ListMembershipsForUser(ctx context.Context, userID uuid.UUID) ([]ListMembershipsForUserRow, error) {
	rows, err := q.db.Query(ctx, listMembershipsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMembershipsForUserRow{}
	for rows.Next() {
		var i ListMembershipsForUserRow
		if err := rows.Scan(
			&i.ProjectID,
			&i.ProjectSlug,
			&i.ProjectName,
			&i.RoleID,
			&i.RoleKey,
			&i.RoleLabel,
			&i.RoleColor,
			&i.RolePosition,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectMembers = `-- name: ListProjectMembers :many
SELECT u.id AS user_id, u.github_login, u.display_name,
       COALESCE(u.avatar_url, '')::text AS avatar_url, u.is_admin,
       r.id AS role_id, r.key AS role_key, r.label AS role_label,
       COALESCE(r.color, '')::text AS role_color
FROM memberships m
JOIN users u ON u.id = m.user_id
JOIN roles r ON r.id = m.role_id
WHERE m.project_id = $1
ORDER BY u.display_name, r.label
`

type ListProjectMembersRow struct {
	UserID      uuid.UUID
	GithubLogin string
	DisplayName string
	AvatarUrl   string
	IsAdmin     bool
	RoleID      uuid.UUID
	RoleKey     string
	RoleLabel   string
	RoleColor   string
}

func (q *Queries) ListProjectMembers(ctx context.Context, projectID uuid.UUID) ([]ListProjectMembersRow, error) {
	rows, err := q.db.Query(ctx, listProjectMembers, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProjectMembersRow{}
	for rows.Next() {
		var i ListProjectMembersRow
		if err := rows.Scan(
			&i.UserID,
			&i.GithubLogin,
			&i.DisplayName,
			&i.AvatarUrl,
			&i.IsAdmin,
			&i.RoleID,
			&i.RoleKey,
			&i.RoleLabel,
			&i.RoleColor,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserRoleIDsInProject = `-- name: ListUserRoleIDsInProject :many
SELECT role_id FROM memberships
WHERE user_id = $1 AND project_id = $2
`

type ListUserRoleIDsInProjectParams struct {
	UserID    uuid.UUID
	ProjectID uuid.UUID
}

func (q *Queries) ListUserRoleIDsInProject(ctx context.Context, arg ListUserRoleIDsInProjectParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listUserRoleIDsInProject, arg.UserID, arg.ProjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var role_id uuid.UUID
		if err := rows.Scan(&role_id); err != nil {
			return nil, err
		}
		items = append(items, role_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
