// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: memberships.sql

package dbq

import (
	"context"

	"github.com/google/uuid"
)

const assignRole = `-- name: AssignRole :exec
INSERT INTO membership_roles (user_id, project_id, role_id)
VALUES ($1, $2, $3)
ON CONFLICT DO NOTHING
`

type AssignRoleParams struct {
	UserID    uuid.UUID
	ProjectID uuid.UUID
	RoleID    uuid.UUID
}

// Grants a specific role to a member. Idempotent.
func (q *Queries) AssignRole(ctx context.Context, arg AssignRoleParams) error {
	_, err := q.db.Exec(ctx, assignRole, arg.UserID, arg.ProjectID, arg.RoleID)
	return err
}

const ensureMembership = `-- name: EnsureMembership :exec
INSERT INTO memberships (user_id, project_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type EnsureMembershipParams struct {
	UserID    uuid.UUID
	ProjectID uuid.UUID
}

// Idempotent: marks the user as a member of the project. Role
// assignments live in a separate table so a membership without any
// roles is a legal state.
func (q *Queries) EnsureMembership(ctx context.Context, arg EnsureMembershipParams) error {
	_, err := q.db.Exec(ctx, ensureMembership, arg.UserID, arg.ProjectID)
	return err
}

const listMembershipsForUser = `-- name: ListMembershipsForUser :many
SELECT p.id AS project_id, p.slug AS project_slug, p.name AS project_name,
       mr.role_id, r.key AS role_key, r.label AS role_label,
       COALESCE(r.color, '')::text AS role_color, r.position AS role_position
FROM memberships m
JOIN projects p ON p.id = m.project_id
JOIN membership_roles mr
     ON mr.user_id = m.user_id AND mr.project_id = m.project_id
JOIN roles r ON r.id = mr.role_id
WHERE m.user_id = $1
ORDER BY p.slug, r.position, r.label
`

type ListMembershipsForUserRow struct {
	ProjectID    uuid.UUID
	ProjectSlug  string
	ProjectName  string
	RoleID       uuid.UUID
	RoleKey      string
	RoleLabel    string
	RoleColor    string
	RolePosition int32
}

// One row per (project, role) the user holds. Projects where the
// user has zero roles are omitted here on purpose — this feeds the
// role-scoped whoami view; use ListProjectIDsForUser to enumerate
// project membership regardless of roles.
func (q *Queries) ListMembershipsForUser(ctx context.Context, userID uuid.UUID) ([]ListMembershipsForUserRow, error) {
	rows, err := q.db.Query(ctx, listMembershipsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMembershipsForUserRow{}
	for rows.Next() {
		var i ListMembershipsForUserRow
		if err := rows.Scan(
			&i.ProjectID,
			&i.ProjectSlug,
			&i.ProjectName,
			&i.RoleID,
			&i.RoleKey,
			&i.RoleLabel,
			&i.RoleColor,
			&i.RolePosition,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectMembers = `-- name: ListProjectMembers :many
SELECT u.id AS user_id, u.github_login, u.display_name,
       COALESCE(u.avatar_url, '')::text AS avatar_url, u.is_admin,
       mr.role_id AS role_id,
       COALESCE(r.key, '')::text     AS role_key,
       COALESCE(r.label, '')::text   AS role_label,
       COALESCE(r.color, '')::text   AS role_color
FROM memberships m
JOIN users u ON u.id = m.user_id
LEFT JOIN membership_roles mr
       ON mr.user_id = m.user_id AND mr.project_id = m.project_id
LEFT JOIN roles r ON r.id = mr.role_id
WHERE m.project_id = $1
ORDER BY u.display_name, r.position NULLS LAST, r.label
`

type ListProjectMembersRow struct {
	UserID      uuid.UUID
	GithubLogin string
	DisplayName string
	AvatarUrl   string
	IsAdmin     bool
	RoleID      *uuid.UUID
	RoleKey     string
	RoleLabel   string
	RoleColor   string
}

// One row per (member, role). A member with no role assignments
// still appears once, with role columns NULL, via LEFT JOIN.
func (q *Queries) ListProjectMembers(ctx context.Context, projectID uuid.UUID) ([]ListProjectMembersRow, error) {
	rows, err := q.db.Query(ctx, listProjectMembers, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProjectMembersRow{}
	for rows.Next() {
		var i ListProjectMembersRow
		if err := rows.Scan(
			&i.UserID,
			&i.GithubLogin,
			&i.DisplayName,
			&i.AvatarUrl,
			&i.IsAdmin,
			&i.RoleID,
			&i.RoleKey,
			&i.RoleLabel,
			&i.RoleColor,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserRoleIDsInProject = `-- name: ListUserRoleIDsInProject :many
SELECT role_id FROM membership_roles
WHERE user_id = $1 AND project_id = $2
`

type ListUserRoleIDsInProjectParams struct {
	UserID    uuid.UUID
	ProjectID uuid.UUID
}

func (q *Queries) ListUserRoleIDsInProject(ctx context.Context, arg ListUserRoleIDsInProjectParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listUserRoleIDsInProject, arg.UserID, arg.ProjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var role_id uuid.UUID
		if err := rows.Scan(&role_id); err != nil {
			return nil, err
		}
		items = append(items, role_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeMembership = `-- name: RemoveMembership :exec
DELETE FROM memberships
WHERE user_id = $1 AND project_id = $2
`

type RemoveMembershipParams struct {
	UserID    uuid.UUID
	ProjectID uuid.UUID
}

// Removes the user from the project entirely; their role assignments
// cascade away via membership_roles_membership_fkey.
func (q *Queries) RemoveMembership(ctx context.Context, arg RemoveMembershipParams) error {
	_, err := q.db.Exec(ctx, removeMembership, arg.UserID, arg.ProjectID)
	return err
}

const unassignRole = `-- name: UnassignRole :exec
DELETE FROM membership_roles
WHERE user_id = $1 AND project_id = $2 AND role_id = $3
`

type UnassignRoleParams struct {
	UserID    uuid.UUID
	ProjectID uuid.UUID
	RoleID    uuid.UUID
}

// Revokes a specific role from a member. The membership row itself
// stays — dropping the last role does NOT remove the member from
// the project.
func (q *Queries) UnassignRole(ctx context.Context, arg UnassignRoleParams) error {
	_, err := q.db.Exec(ctx, unassignRole, arg.UserID, arg.ProjectID, arg.RoleID)
	return err
}
