// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbq

import (
	"net/netip"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type ApiToken struct {
	ID            uuid.UUID
	UserID        uuid.UUID
	Name          string
	TokenHash     []byte
	Prefix        string
	DefaultRoleID *uuid.UUID
	CreatedAt     pgtype.Timestamptz
	LastUsedAt    pgtype.Timestamptz
	RevokedAt     pgtype.Timestamptz
}

type ArchEdge struct {
	ID            uuid.UUID
	ProjectID     uuid.UUID
	FromNodeID    uuid.UUID
	ToNodeID      uuid.UUID
	Kind          string
	Label         string
	DescriptionMd string
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
}

type ArchNode struct {
	ID            uuid.UUID
	ProjectID     uuid.UUID
	Slug          string
	ParentID      *uuid.UUID
	Kind          string
	Name          string
	DescriptionMd string
	Metadata      []byte
	LinkedRepo    pgtype.Text
	LinkedPath    pgtype.Text
	Position      int32
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
	SearchVector  interface{}
}

type ArchNodeKind struct {
	ProjectID   uuid.UUID
	Key         string
	Label       string
	Icon        string
	Color       string
	Description string
	IsDefault   bool
	CreatedAt   pgtype.Timestamptz
}

type ArchNodeLink struct {
	ProjectID uuid.UUID
	NodeID    uuid.UUID
	LinkType  string
	TargetID  string
	CreatedAt pgtype.Timestamptz
}

type Cycle struct {
	ID              uuid.UUID
	ProjectID       uuid.UUID
	Name            string
	Position        int32
	OpenedAt        pgtype.Timestamptz
	ClosedAt        pgtype.Timestamptz
	ClosedByUserID  *uuid.UUID
	ClosedByTokenID *uuid.UUID
}

type Document struct {
	ID               uuid.UUID
	Scope            string
	ProjectID        *uuid.UUID
	Path             string
	Kind             string
	Title            string
	Description      string
	ContentMd        string
	Frontmatter      []byte
	CurrentVersion   int32
	DeletedAt        pgtype.Timestamptz
	CreatedByUserID  *uuid.UUID
	CreatedByTokenID *uuid.UUID
	UpdatedByUserID  *uuid.UUID
	UpdatedByTokenID *uuid.UUID
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
	SearchVector     interface{}
}

type DocumentVersion struct {
	ID            uuid.UUID
	DocumentID    uuid.UUID
	Version       int32
	Title         string
	Description   string
	ContentMd     string
	Frontmatter   []byte
	Message       string
	AuthorUserID  *uuid.UUID
	AuthorTokenID *uuid.UUID
	CreatedAt     pgtype.Timestamptz
}

type InstanceMetum struct {
	Key   string
	Value string
}

type Membership struct {
	UserID    uuid.UUID
	ProjectID uuid.UUID
	RoleID    uuid.UUID
	CreatedAt pgtype.Timestamptz
}

type Project struct {
	ID              uuid.UUID
	Slug            string
	Name            string
	Description     string
	PrimaryLanguage pgtype.Text
	ProjectType     pgtype.Text
	CreatedByUserID *uuid.UUID
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
	McpPageSize     int32
	DefaultView     string
	CycleLabel      string
	OwnerUserID     uuid.UUID
}

type ProjectPriority struct {
	ProjectID uuid.UUID
	Key       string
	Value     int32
	Position  int32
	IsDefault bool
	CreatedAt pgtype.Timestamptz
}

type ProjectRepo struct {
	ProjectID uuid.UUID
	Repo      string
	AddedAt   pgtype.Timestamptz
}

type Role struct {
	ID        uuid.UUID
	ProjectID uuid.UUID
	Key       string
	Label     string
	Color     pgtype.Text
	CreatedAt pgtype.Timestamptz
	Position  int32
}

type Session struct {
	ID         uuid.UUID
	UserID     uuid.UUID
	CreatedAt  pgtype.Timestamptz
	LastSeenAt pgtype.Timestamptz
	ExpiresAt  pgtype.Timestamptz
	UserAgent  pgtype.Text
	Ip         *netip.Addr
}

type Task struct {
	ID               uuid.UUID
	ProjectID        uuid.UUID
	ParentTaskID     *uuid.UUID
	Type             string
	Title            string
	DescriptionMd    string
	State            string
	Priority         int32
	AssigneeUserID   *uuid.UUID
	TargetRoleID     *uuid.UUID
	ActualStart      pgtype.Timestamptz
	ActualEnd        pgtype.Timestamptz
	CreatedByUserID  *uuid.UUID
	CreatedByTokenID *uuid.UUID
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
	SearchVector     interface{}
}

type TaskComment struct {
	ID            uuid.UUID
	TaskID        uuid.UUID
	AuthorUserID  *uuid.UUID
	AuthorTokenID *uuid.UUID
	BodyMd        string
	CreatedAt     pgtype.Timestamptz
}

type TaskCommit struct {
	TaskID         uuid.UUID
	Repo           string
	Sha            string
	Message        string
	AddedAt        pgtype.Timestamptz
	AddedByUserID  *uuid.UUID
	AddedByTokenID *uuid.UUID
}

type TaskDependency struct {
	TaskID      uuid.UUID
	DependsOnID uuid.UUID
}

type User struct {
	ID          uuid.UUID
	GithubLogin string
	GithubID    int64
	DisplayName string
	AvatarUrl   pgtype.Text
	IsAdmin     bool
	CreatedAt   pgtype.Timestamptz
	LastSeenAt  pgtype.Timestamptz
}
