// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notifications.sql

package dbq

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countUnread = `-- name: CountUnread :one
SELECT COUNT(*)::int AS unread
FROM notifications
WHERE user_id = $1::uuid
  AND read_at IS NULL
`

func (q *Queries) CountUnread(ctx context.Context, userID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, countUnread, userID)
	var unread int32
	err := row.Scan(&unread)
	return unread, err
}

const getPreferences = `-- name: GetPreferences :one
SELECT notification_preferences
FROM users
WHERE id = $1::uuid
`

func (q *Queries) GetPreferences(ctx context.Context, userID uuid.UUID) ([]byte, error) {
	row := q.db.QueryRow(ctx, getPreferences, userID)
	var notification_preferences []byte
	err := row.Scan(&notification_preferences)
	return notification_preferences, err
}

const insertNotification = `-- name: InsertNotification :one
INSERT INTO notifications (
  user_id, project_id, kind, task_id, actor_user_id, body
) VALUES (
  $1::uuid,
  $2::uuid,
  $3::text,
  $4::uuid,
  $5::uuid,
  $6::text
)
RETURNING id, user_id, project_id, kind, task_id, actor_user_id, body, created_at, read_at
`

type InsertNotificationParams struct {
	UserID      uuid.UUID
	ProjectID   uuid.UUID
	Kind        string
	TaskID      *uuid.UUID
	ActorUserID *uuid.UUID
	Body        string
}

func (q *Queries) InsertNotification(ctx context.Context, arg InsertNotificationParams) (Notification, error) {
	row := q.db.QueryRow(ctx, insertNotification,
		arg.UserID,
		arg.ProjectID,
		arg.Kind,
		arg.TaskID,
		arg.ActorUserID,
		arg.Body,
	)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProjectID,
		&i.Kind,
		&i.TaskID,
		&i.ActorUserID,
		&i.Body,
		&i.CreatedAt,
		&i.ReadAt,
	)
	return i, err
}

const listNotifications = `-- name: ListNotifications :many
SELECT id, user_id, project_id, kind, task_id, actor_user_id, body, created_at, read_at
FROM notifications
WHERE user_id = $1::uuid
  AND (
    $2::timestamptz IS NULL
    OR created_at < $2::timestamptz
    OR (created_at = $2::timestamptz
        AND id > $3::uuid)
  )
ORDER BY created_at DESC, id ASC
LIMIT $4::int
`

type ListNotificationsParams struct {
	UserID         uuid.UUID
	AfterCreatedAt pgtype.Timestamptz
	AfterID        *uuid.UUID
	Lim            int32
}

// Keyset paginated by (created_at DESC, id ASC). Pass after_created_at
// and after_id from a previous page's tail row; NULL on the first page.
// Requests limit+1 so the caller can detect has_more (last row dropped).
func (q *Queries) ListNotifications(ctx context.Context, arg ListNotificationsParams) ([]Notification, error) {
	rows, err := q.db.Query(ctx, listNotifications,
		arg.UserID,
		arg.AfterCreatedAt,
		arg.AfterID,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Notification{}
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ProjectID,
			&i.Kind,
			&i.TaskID,
			&i.ActorUserID,
			&i.Body,
			&i.CreatedAt,
			&i.ReadAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAllRead = `-- name: MarkAllRead :execrows
UPDATE notifications
SET read_at = now()
WHERE user_id = $1::uuid
  AND read_at IS NULL
`

func (q *Queries) MarkAllRead(ctx context.Context, userID uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, markAllRead, userID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markRead = `-- name: MarkRead :execrows
UPDATE notifications
SET read_at = now()
WHERE user_id = $1::uuid
  AND id = ANY($2::uuid[])
  AND read_at IS NULL
`

type MarkReadParams struct {
	UserID uuid.UUID
	Ids    []uuid.UUID
}

func (q *Queries) MarkRead(ctx context.Context, arg MarkReadParams) (int64, error) {
	result, err := q.db.Exec(ctx, markRead, arg.UserID, arg.Ids)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updatePreferences = `-- name: UpdatePreferences :exec
UPDATE users
SET notification_preferences = $1::jsonb
WHERE id = $2::uuid
`

type UpdatePreferencesParams struct {
	Prefs  []byte
	UserID uuid.UUID
}

func (q *Queries) UpdatePreferences(ctx context.Context, arg UpdatePreferencesParams) error {
	_, err := q.db.Exec(ctx, updatePreferences, arg.Prefs, arg.UserID)
	return err
}
