// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: priorities.sql

package dbq

import (
	"context"

	"github.com/google/uuid"
)

const deleteProjectPriority = `-- name: DeleteProjectPriority :execrows
DELETE FROM project_priorities WHERE project_id = $1 AND key = $2
`

type DeleteProjectPriorityParams struct {
	ProjectID uuid.UUID
	Key       string
}

func (q *Queries) DeleteProjectPriority(ctx context.Context, arg DeleteProjectPriorityParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteProjectPriority, arg.ProjectID, arg.Key)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getPriorityClosestTo50 = `-- name: GetPriorityClosestTo50 :one
SELECT value FROM project_priorities
WHERE project_id = $1
ORDER BY abs(value - 50) ASC, value DESC
LIMIT 1
`

func (q *Queries) GetPriorityClosestTo50(ctx context.Context, projectID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, getPriorityClosestTo50, projectID)
	var value int32
	err := row.Scan(&value)
	return value, err
}

const getPriorityValue = `-- name: GetPriorityValue :one
SELECT value FROM project_priorities WHERE project_id = $1 AND key = $2
`

type GetPriorityValueParams struct {
	ProjectID uuid.UUID
	Key       string
}

func (q *Queries) GetPriorityValue(ctx context.Context, arg GetPriorityValueParams) (int32, error) {
	row := q.db.QueryRow(ctx, getPriorityValue, arg.ProjectID, arg.Key)
	var value int32
	err := row.Scan(&value)
	return value, err
}

const listProjectPriorities = `-- name: ListProjectPriorities :many
SELECT project_id, key, value, position, is_default
FROM project_priorities
WHERE project_id = $1
ORDER BY position, value DESC
`

type ListProjectPrioritiesRow struct {
	ProjectID uuid.UUID
	Key       string
	Value     int32
	Position  int32
	IsDefault bool
}

func (q *Queries) ListProjectPriorities(ctx context.Context, projectID uuid.UUID) ([]ListProjectPrioritiesRow, error) {
	rows, err := q.db.Query(ctx, listProjectPriorities, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProjectPrioritiesRow{}
	for rows.Next() {
		var i ListProjectPrioritiesRow
		if err := rows.Scan(
			&i.ProjectID,
			&i.Key,
			&i.Value,
			&i.Position,
			&i.IsDefault,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const seedDefaultPriority = `-- name: SeedDefaultPriority :exec
INSERT INTO project_priorities (project_id, key, value, position, is_default)
VALUES ($1, $2, $3, $4, true)
ON CONFLICT DO NOTHING
`

type SeedDefaultPriorityParams struct {
	ProjectID uuid.UUID
	Key       string
	Value     int32
	Position  int32
}

func (q *Queries) SeedDefaultPriority(ctx context.Context, arg SeedDefaultPriorityParams) error {
	_, err := q.db.Exec(ctx, seedDefaultPriority,
		arg.ProjectID,
		arg.Key,
		arg.Value,
		arg.Position,
	)
	return err
}

const upsertProjectPriority = `-- name: UpsertProjectPriority :one
INSERT INTO project_priorities (project_id, key, value, position, is_default)
VALUES ($1, $2, $3, $4, false)
ON CONFLICT (project_id, key) DO UPDATE
  SET value = EXCLUDED.value, position = EXCLUDED.position
RETURNING project_id, key, value, position, is_default
`

type UpsertProjectPriorityParams struct {
	ProjectID uuid.UUID
	Key       string
	Value     int32
	Position  int32
}

type UpsertProjectPriorityRow struct {
	ProjectID uuid.UUID
	Key       string
	Value     int32
	Position  int32
	IsDefault bool
}

func (q *Queries) UpsertProjectPriority(ctx context.Context, arg UpsertProjectPriorityParams) (UpsertProjectPriorityRow, error) {
	row := q.db.QueryRow(ctx, upsertProjectPriority,
		arg.ProjectID,
		arg.Key,
		arg.Value,
		arg.Position,
	)
	var i UpsertProjectPriorityRow
	err := row.Scan(
		&i.ProjectID,
		&i.Key,
		&i.Value,
		&i.Position,
		&i.IsDefault,
	)
	return i, err
}
