// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: projects.sql

package dbq

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const clearProjectRepos = `-- name: ClearProjectRepos :exec
DELETE FROM project_repos WHERE project_id = $1
`

func (q *Queries) ClearProjectRepos(ctx context.Context, projectID uuid.UUID) error {
	_, err := q.db.Exec(ctx, clearProjectRepos, projectID)
	return err
}

const deleteProjectByID = `-- name: DeleteProjectByID :exec
DELETE FROM projects WHERE id = $1
`

func (q *Queries) DeleteProjectByID(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteProjectByID, id)
	return err
}

const getProjectByIDOrSlug = `-- name: GetProjectByIDOrSlug :one
SELECT id, slug, name, description,
       COALESCE(primary_language, '')::text AS primary_language,
       COALESCE(project_type, '')::text AS project_type,
       mcp_page_size, default_view,
       created_by_user_id, created_at, updated_at
FROM projects
WHERE id::text = $1::text
   OR slug      = $1::text
`

type GetProjectByIDOrSlugRow struct {
	ID              uuid.UUID
	Slug            string
	Name            string
	Description     string
	PrimaryLanguage string
	ProjectType     string
	McpPageSize     int32
	DefaultView     string
	CreatedByUserID *uuid.UUID
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

func (q *Queries) GetProjectByIDOrSlug(ctx context.Context, idOrSlug string) (GetProjectByIDOrSlugRow, error) {
	row := q.db.QueryRow(ctx, getProjectByIDOrSlug, idOrSlug)
	var i GetProjectByIDOrSlugRow
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.PrimaryLanguage,
		&i.ProjectType,
		&i.McpPageSize,
		&i.DefaultView,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertProject = `-- name: InsertProject :one
INSERT INTO projects (slug, name, description, primary_language, project_type, created_by_user_id)
VALUES ($1, $2, $3, NULLIF($5::text, ''),
        NULLIF($6::text, ''), $4)
RETURNING id, slug, name, description,
          COALESCE(primary_language, '')::text AS primary_language,
          COALESCE(project_type, '')::text AS project_type,
          mcp_page_size, default_view,
          created_by_user_id, created_at, updated_at
`

type InsertProjectParams struct {
	Slug            string
	Name            string
	Description     string
	CreatedByUserID *uuid.UUID
	PrimaryLanguage string
	ProjectType     string
}

type InsertProjectRow struct {
	ID              uuid.UUID
	Slug            string
	Name            string
	Description     string
	PrimaryLanguage string
	ProjectType     string
	McpPageSize     int32
	DefaultView     string
	CreatedByUserID *uuid.UUID
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

func (q *Queries) InsertProject(ctx context.Context, arg InsertProjectParams) (InsertProjectRow, error) {
	row := q.db.QueryRow(ctx, insertProject,
		arg.Slug,
		arg.Name,
		arg.Description,
		arg.CreatedByUserID,
		arg.PrimaryLanguage,
		arg.ProjectType,
	)
	var i InsertProjectRow
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.PrimaryLanguage,
		&i.ProjectType,
		&i.McpPageSize,
		&i.DefaultView,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertProjectRepo = `-- name: InsertProjectRepo :exec
INSERT INTO project_repos (project_id, repo)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type InsertProjectRepoParams struct {
	ProjectID uuid.UUID
	Repo      string
}

func (q *Queries) InsertProjectRepo(ctx context.Context, arg InsertProjectRepoParams) error {
	_, err := q.db.Exec(ctx, insertProjectRepo, arg.ProjectID, arg.Repo)
	return err
}

const listProjectRepos = `-- name: ListProjectRepos :many
SELECT repo FROM project_repos WHERE project_id = $1 ORDER BY repo
`

func (q *Queries) ListProjectRepos(ctx context.Context, projectID uuid.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, listProjectRepos, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var repo string
		if err := rows.Scan(&repo); err != nil {
			return nil, err
		}
		items = append(items, repo)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectsAdmin = `-- name: ListProjectsAdmin :many
SELECT id, slug, name, description,
       COALESCE(primary_language, '')::text AS primary_language,
       COALESCE(project_type, '')::text AS project_type,
       mcp_page_size, default_view,
       created_by_user_id, created_at, updated_at
FROM projects
ORDER BY name
`

type ListProjectsAdminRow struct {
	ID              uuid.UUID
	Slug            string
	Name            string
	Description     string
	PrimaryLanguage string
	ProjectType     string
	McpPageSize     int32
	DefaultView     string
	CreatedByUserID *uuid.UUID
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

func (q *Queries) ListProjectsAdmin(ctx context.Context) ([]ListProjectsAdminRow, error) {
	rows, err := q.db.Query(ctx, listProjectsAdmin)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProjectsAdminRow{}
	for rows.Next() {
		var i ListProjectsAdminRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.Description,
			&i.PrimaryLanguage,
			&i.ProjectType,
			&i.McpPageSize,
			&i.DefaultView,
			&i.CreatedByUserID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectsForUser = `-- name: ListProjectsForUser :many
SELECT DISTINCT p.id, p.slug, p.name, p.description,
       COALESCE(p.primary_language, '')::text AS primary_language,
       COALESCE(p.project_type, '')::text AS project_type,
       p.mcp_page_size, p.default_view,
       p.created_by_user_id, p.created_at, p.updated_at
FROM projects p
JOIN memberships m ON m.project_id = p.id
WHERE m.user_id = $1
ORDER BY p.name
`

type ListProjectsForUserRow struct {
	ID              uuid.UUID
	Slug            string
	Name            string
	Description     string
	PrimaryLanguage string
	ProjectType     string
	McpPageSize     int32
	DefaultView     string
	CreatedByUserID *uuid.UUID
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

func (q *Queries) ListProjectsForUser(ctx context.Context, userID uuid.UUID) ([]ListProjectsForUserRow, error) {
	rows, err := q.db.Query(ctx, listProjectsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProjectsForUserRow{}
	for rows.Next() {
		var i ListProjectsForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.Description,
			&i.PrimaryLanguage,
			&i.ProjectType,
			&i.McpPageSize,
			&i.DefaultView,
			&i.CreatedByUserID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const projectSlugExists = `-- name: ProjectSlugExists :one
SELECT EXISTS (SELECT 1 FROM projects WHERE slug = $1)::bool
`

func (q *Queries) ProjectSlugExists(ctx context.Context, slug string) (bool, error) {
	row := q.db.QueryRow(ctx, projectSlugExists, slug)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const updateProjectDefaultView = `-- name: UpdateProjectDefaultView :exec
UPDATE projects SET default_view = $1::text, updated_at = now()
WHERE id = $2::uuid
`

type UpdateProjectDefaultViewParams struct {
	DefaultView string
	ID          uuid.UUID
}

func (q *Queries) UpdateProjectDefaultView(ctx context.Context, arg UpdateProjectDefaultViewParams) error {
	_, err := q.db.Exec(ctx, updateProjectDefaultView, arg.DefaultView, arg.ID)
	return err
}

const updateProjectFields = `-- name: UpdateProjectFields :exec
UPDATE projects
SET name = $2,
    description = $3,
    primary_language = NULLIF($4::text, ''),
    project_type = NULLIF($5::text, ''),
    updated_at = now()
WHERE id = $1
`

type UpdateProjectFieldsParams struct {
	ID              uuid.UUID
	Name            string
	Description     string
	PrimaryLanguage string
	ProjectType     string
}

func (q *Queries) UpdateProjectFields(ctx context.Context, arg UpdateProjectFieldsParams) error {
	_, err := q.db.Exec(ctx, updateProjectFields,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.PrimaryLanguage,
		arg.ProjectType,
	)
	return err
}

const updateProjectMCPPageSize = `-- name: UpdateProjectMCPPageSize :exec
UPDATE projects SET mcp_page_size = $2, updated_at = now() WHERE id = $1
`

type UpdateProjectMCPPageSizeParams struct {
	ID          uuid.UUID
	McpPageSize int32
}

func (q *Queries) UpdateProjectMCPPageSize(ctx context.Context, arg UpdateProjectMCPPageSizeParams) error {
	_, err := q.db.Exec(ctx, updateProjectMCPPageSize, arg.ID, arg.McpPageSize)
	return err
}
