// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbq

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AcquireDepLock(ctx context.Context, arg AcquireDepLockParams) error
	// Atomic claim: same eligibility filter as NextEligibleTask, picked
	// via SELECT … FOR UPDATE SKIP LOCKED so two concurrent agents never
	// claim the same row. Marks the row assignee = caller, state = doing,
	// actual_start filled if previously null, all in one UPDATE.
	ClaimNextEligibleTask(ctx context.Context, arg ClaimNextEligibleTaskParams) (ClaimNextEligibleTaskRow, error)
	ClaimTask(ctx context.Context, arg ClaimTaskParams) error
	ClearProjectRepos(ctx context.Context, projectID uuid.UUID) error
	CountNonDoneChildren(ctx context.Context, parentTaskID *uuid.UUID) (int32, error)
	CountUsers(ctx context.Context) (int32, error)
	DeleteMembership(ctx context.Context, arg DeleteMembershipParams) error
	DeleteProjectByID(ctx context.Context, id uuid.UUID) error
	DeleteProjectPriority(ctx context.Context, arg DeleteProjectPriorityParams) (int64, error)
	DeleteProjectRole(ctx context.Context, id uuid.UUID) error
	DeleteTask(ctx context.Context, id uuid.UUID) (int64, error)
	DeleteTaskCommit(ctx context.Context, arg DeleteTaskCommitParams) error
	GetParentStateAndGrandparent(ctx context.Context, id uuid.UUID) (GetParentStateAndGrandparentRow, error)
	GetPriorityClosestTo50(ctx context.Context, projectID uuid.UUID) (int32, error)
	GetPriorityValue(ctx context.Context, arg GetPriorityValueParams) (int32, error)
	GetProjectByIDOrSlug(ctx context.Context, idOrSlug string) (GetProjectByIDOrSlugRow, error)
	GetTask(ctx context.Context, id uuid.UUID) (GetTaskRow, error)
	GetTaskForUpdate(ctx context.Context, id uuid.UUID) (GetTaskForUpdateRow, error)
	GetUserByGithubID(ctx context.Context, githubID int64) (GetUserByGithubIDRow, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (GetUserByIDRow, error)
	InsertDependency(ctx context.Context, arg InsertDependencyParams) (int64, error)
	InsertMembership(ctx context.Context, arg InsertMembershipParams) error
	InsertProject(ctx context.Context, arg InsertProjectParams) (InsertProjectRow, error)
	InsertProjectRepo(ctx context.Context, arg InsertProjectRepoParams) error
	InsertProjectRole(ctx context.Context, arg InsertProjectRoleParams) (InsertProjectRoleRow, error)
	InsertSeedRole(ctx context.Context, arg InsertSeedRoleParams) error
	InsertTask(ctx context.Context, arg InsertTaskParams) (InsertTaskRow, error)
	InsertTaskComment(ctx context.Context, arg InsertTaskCommentParams) (TaskComment, error)
	InsertUser(ctx context.Context, arg InsertUserParams) (InsertUserRow, error)
	ListDependents(ctx context.Context, dependsOnID uuid.UUID) ([]uuid.UUID, error)
	ListDependsOn(ctx context.Context, taskID uuid.UUID) ([]uuid.UUID, error)
	ListMembershipsForUser(ctx context.Context, userID uuid.UUID) ([]ListMembershipsForUserRow, error)
	ListProjectDependencies(ctx context.Context, projectID uuid.UUID) ([]TaskDependency, error)
	ListProjectMembers(ctx context.Context, projectID uuid.UUID) ([]ListProjectMembersRow, error)
	ListProjectPriorities(ctx context.Context, projectID uuid.UUID) ([]ListProjectPrioritiesRow, error)
	ListProjectRepos(ctx context.Context, projectID uuid.UUID) ([]string, error)
	ListProjectRoleIDs(ctx context.Context, projectID uuid.UUID) ([]uuid.UUID, error)
	ListProjectRoles(ctx context.Context, projectID uuid.UUID) ([]ListProjectRolesRow, error)
	ListProjectsAdmin(ctx context.Context) ([]ListProjectsAdminRow, error)
	ListProjectsForUser(ctx context.Context, userID uuid.UUID) ([]ListProjectsForUserRow, error)
	ListTaskComments(ctx context.Context, taskID uuid.UUID) ([]TaskComment, error)
	ListTaskCommits(ctx context.Context, taskID uuid.UUID) ([]ListTaskCommitsRow, error)
	// Optional filters: state, type, assignee, target_role, parent_task.
	// include_children=false (default) restricts to parent IS NULL UNLESS
	// parent_task_id is explicitly set.
	ListTasks(ctx context.Context, arg ListTasksParams) ([]ListTasksRow, error)
	// Same filters as ListTasks plus keyset cursor on (priority DESC,
	// created_at ASC, id ASC). The cursor params are all-or-nothing:
	// pass them together or all NULL for the first page. The caller
	// requests limit+1 rows to detect has_more.
	ListTasksPaginated(ctx context.Context, arg ListTasksPaginatedParams) ([]ListTasksPaginatedRow, error)
	ListUnresolvedPreconditions(ctx context.Context, taskID uuid.UUID) ([]ListUnresolvedPreconditionsRow, error)
	ListUserRoleIDsInProject(ctx context.Context, arg ListUserRoleIDsInProjectParams) ([]uuid.UUID, error)
	LockTaskRow(ctx context.Context, id uuid.UUID) error
	LockTaskTypeAndParent(ctx context.Context, id uuid.UUID) (LockTaskTypeAndParentRow, error)
	LockTwoTaskRows(ctx context.Context, ids []uuid.UUID) ([]uuid.UUID, error)
	// Preview: returns the next pickable task without claiming it. Same
	// eligibility rules as ClaimNextEligibleTask but no row lock and no
	// mutation. Use ClaimNextEligibleTask for atomic pickup.
	NextEligibleTask(ctx context.Context, arg NextEligibleTaskParams) (NextEligibleTaskRow, error)
	ProjectIDForTask(ctx context.Context, id uuid.UUID) (uuid.UUID, error)
	ProjectSlugExists(ctx context.Context, slug string) (bool, error)
	RemoveDependency(ctx context.Context, arg RemoveDependencyParams) (int64, error)
	RoleExistsInProject(ctx context.Context, arg RoleExistsInProjectParams) (bool, error)
	SeedDefaultPriority(ctx context.Context, arg SeedDefaultPriorityParams) error
	SetRolePosition(ctx context.Context, arg SetRolePositionParams) error
	SetTaskDoing(ctx context.Context, id uuid.UUID) error
	SetTaskDone(ctx context.Context, id uuid.UUID) error
	SetTaskTodo(ctx context.Context, id uuid.UUID) error
	TouchUserLastSeen(ctx context.Context, id uuid.UUID) error
	UpdateProjectFields(ctx context.Context, arg UpdateProjectFieldsParams) error
	UpdateProjectMCPPageSize(ctx context.Context, arg UpdateProjectMCPPageSizeParams) error
	UpdateProjectRole(ctx context.Context, arg UpdateProjectRoleParams) (UpdateProjectRoleRow, error)
	// Optional fields: title, description, type, priority, assignee_user_id,
	// target_role_id. assignee/target_role have an explicit "unset"
	// boolean because COALESCE alone can't distinguish "leave alone" from
	// "set to NULL".
	UpdateTaskFields(ctx context.Context, arg UpdateTaskFieldsParams) (UpdateTaskFieldsRow, error)
	UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) error
	UpsertProjectPriority(ctx context.Context, arg UpsertProjectPriorityParams) (UpsertProjectPriorityRow, error)
	UpsertTaskCommit(ctx context.Context, arg UpsertTaskCommitParams) error
	UserBelongsToProjectOrIsAdmin(ctx context.Context, arg UserBelongsToProjectOrIsAdminParams) (bool, error)
	WouldCreateCycle(ctx context.Context, arg WouldCreateCycleParams) (pgtype.Bool, error)
}

var _ Querier = (*Queries)(nil)
