// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: roles.sql

package dbq

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const deleteProjectRole = `-- name: DeleteProjectRole :exec
DELETE FROM roles WHERE id = $1
`

func (q *Queries) DeleteProjectRole(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteProjectRole, id)
	return err
}

const insertProjectRole = `-- name: InsertProjectRole :one
INSERT INTO roles (project_id, key, label, color, position)
VALUES (
  $1, $2, $3, NULLIF($4::text, ''),
  COALESCE((SELECT MAX(position) + 1 FROM roles WHERE project_id = $1), 0)
)
RETURNING id, project_id, key, label, COALESCE(color, '')::text AS color, position, created_at
`

type InsertProjectRoleParams struct {
	ProjectID uuid.UUID
	Key       string
	Label     string
	Color     string
}

type InsertProjectRoleRow struct {
	ID        uuid.UUID
	ProjectID uuid.UUID
	Key       string
	Label     string
	Color     string
	Position  int32
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) InsertProjectRole(ctx context.Context, arg InsertProjectRoleParams) (InsertProjectRoleRow, error) {
	row := q.db.QueryRow(ctx, insertProjectRole,
		arg.ProjectID,
		arg.Key,
		arg.Label,
		arg.Color,
	)
	var i InsertProjectRoleRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Key,
		&i.Label,
		&i.Color,
		&i.Position,
		&i.CreatedAt,
	)
	return i, err
}

const insertSeedRole = `-- name: InsertSeedRole :one
INSERT INTO roles (project_id, key, label, color, position)
VALUES ($1, $2, $3, $4, $5)
RETURNING id
`

type InsertSeedRoleParams struct {
	ProjectID uuid.UUID
	Key       string
	Label     string
	Color     pgtype.Text
	Position  int32
}

func (q *Queries) InsertSeedRole(ctx context.Context, arg InsertSeedRoleParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, insertSeedRole,
		arg.ProjectID,
		arg.Key,
		arg.Label,
		arg.Color,
		arg.Position,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const listProjectRoleIDs = `-- name: ListProjectRoleIDs :many
SELECT id FROM roles WHERE project_id = $1 ORDER BY created_at, id
`

func (q *Queries) ListProjectRoleIDs(ctx context.Context, projectID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listProjectRoleIDs, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectRoles = `-- name: ListProjectRoles :many
SELECT id, project_id, key, label, COALESCE(color, '')::text AS color, position, created_at
FROM roles
WHERE project_id = $1
ORDER BY position, label
`

type ListProjectRolesRow struct {
	ID        uuid.UUID
	ProjectID uuid.UUID
	Key       string
	Label     string
	Color     string
	Position  int32
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) ListProjectRoles(ctx context.Context, projectID uuid.UUID) ([]ListProjectRolesRow, error) {
	rows, err := q.db.Query(ctx, listProjectRoles, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProjectRolesRow{}
	for rows.Next() {
		var i ListProjectRolesRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Key,
			&i.Label,
			&i.Color,
			&i.Position,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setRolePosition = `-- name: SetRolePosition :exec
UPDATE roles SET position = $2 WHERE id = $1
`

type SetRolePositionParams struct {
	ID       uuid.UUID
	Position int32
}

func (q *Queries) SetRolePosition(ctx context.Context, arg SetRolePositionParams) error {
	_, err := q.db.Exec(ctx, setRolePosition, arg.ID, arg.Position)
	return err
}

const updateProjectRole = `-- name: UpdateProjectRole :one
UPDATE roles
SET label = $2, color = NULLIF($3::text, '')
WHERE id = $1
RETURNING id, project_id, key, label, COALESCE(color, '')::text AS color, position, created_at
`

type UpdateProjectRoleParams struct {
	ID    uuid.UUID
	Label string
	Color string
}

type UpdateProjectRoleRow struct {
	ID        uuid.UUID
	ProjectID uuid.UUID
	Key       string
	Label     string
	Color     string
	Position  int32
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) UpdateProjectRole(ctx context.Context, arg UpdateProjectRoleParams) (UpdateProjectRoleRow, error) {
	row := q.db.QueryRow(ctx, updateProjectRole, arg.ID, arg.Label, arg.Color)
	var i UpdateProjectRoleRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Key,
		&i.Label,
		&i.Color,
		&i.Position,
		&i.CreatedAt,
	)
	return i, err
}
