// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: search.sql

package dbq

import (
	"context"

	"github.com/google/uuid"
)

const unifiedSearch = `-- name: UnifiedSearch :many
WITH q AS (SELECT plainto_tsquery('simple', $2::text) AS tsq)
(
    SELECT 'task'::text AS kind,
           project_id::text AS project_id,
           ts_rank(search_vector, (SELECT tsq FROM q))::real AS rank,
           title,
           left(coalesce(description_md, ''), 400) AS description,
           ts_headline('simple', title, (SELECT tsq FROM q),
             'StartSel=«MARK»,StopSel=«/MARK»,MaxFragments=1,MaxWords=15,MinWords=5'
           ) AS title_headline,
           ts_headline('simple', left(coalesce(description_md, ''), 400), (SELECT tsq FROM q),
             'StartSel=«MARK»,StopSel=«/MARK»,MaxFragments=2,MaxWords=20,MinWords=8,FragmentDelimiter=" … "'
           ) AS description_headline,
           id::text AS task_id,
           ''::text AS doc_path, ''::text AS doc_scope,
           ''::text AS node_slug, ''::text AS node_kind,
           state AS task_state, type AS task_type
    FROM tasks
    WHERE project_id = $3::uuid
      AND search_vector @@ (SELECT tsq FROM q)
      AND $4::bool
)
UNION ALL
(
    SELECT 'document'::text AS kind,
           coalesce(project_id::text, '') AS project_id,
           ts_rank(search_vector, (SELECT tsq FROM q))::real AS rank,
           title,
           left(coalesce(description, ''), 400) AS description,
           ts_headline('simple', title, (SELECT tsq FROM q),
             'StartSel=«MARK»,StopSel=«/MARK»,MaxFragments=1,MaxWords=15,MinWords=5'
           ) AS title_headline,
           ts_headline('simple', left(coalesce(description, ''), 400), (SELECT tsq FROM q),
             'StartSel=«MARK»,StopSel=«/MARK»,MaxFragments=2,MaxWords=20,MinWords=8,FragmentDelimiter=" … "'
           ) AS description_headline,
           ''::text AS task_id,
           path AS doc_path, scope AS doc_scope,
           ''::text AS node_slug, ''::text AS node_kind,
           ''::text AS task_state, ''::text AS task_type
    FROM documents
    WHERE (project_id = $3::uuid OR scope = 'global')
      AND deleted_at IS NULL
      AND search_vector @@ (SELECT tsq FROM q)
      AND $5::bool
)
UNION ALL
(
    SELECT 'arch_node'::text AS kind,
           project_id::text AS project_id,
           ts_rank(search_vector, (SELECT tsq FROM q))::real AS rank,
           name AS title,
           left(coalesce(description_md, ''), 400) AS description,
           ts_headline('simple', name, (SELECT tsq FROM q),
             'StartSel=«MARK»,StopSel=«/MARK»,MaxFragments=1,MaxWords=15,MinWords=5'
           ) AS title_headline,
           ts_headline('simple', left(coalesce(description_md, ''), 400), (SELECT tsq FROM q),
             'StartSel=«MARK»,StopSel=«/MARK»,MaxFragments=2,MaxWords=20,MinWords=8,FragmentDelimiter=" … "'
           ) AS description_headline,
           ''::text AS task_id,
           ''::text AS doc_path, ''::text AS doc_scope,
           slug AS node_slug, kind AS node_kind,
           ''::text AS task_state, ''::text AS task_type
    FROM arch_nodes
    WHERE project_id = $3::uuid
      AND search_vector @@ (SELECT tsq FROM q)
      AND $6::bool
)
ORDER BY rank DESC
LIMIT $1::int
`

type UnifiedSearchParams struct {
	Lim             int32
	Query           string
	ProjectID       uuid.UUID
	IncludeTask     bool
	IncludeDocument bool
	IncludeArchNode bool
}

type UnifiedSearchRow struct {
	Kind                string
	ProjectID           string
	Rank                float32
	Title               string
	Description         string
	TitleHeadline       []byte
	DescriptionHeadline []byte
	TaskID              string
	DocPath             string
	DocScope            string
	NodeSlug            string
	NodeKind            string
	TaskState           string
	TaskType            string
}

// Each domain returns the same shape, plus title_headline /
// description_headline computed with ts_headline. The headline
// options use rare sentinel strings («MARK» / «/MARK») instead of
// HTML tags so the Go layer can html-escape the result safely and
// only then swap the sentinels for <mark>...</mark>. This keeps any
// raw '<' or '>' in user content escaped while still producing
// highlighted snippets the UI can render with unsafeHTML.
func (q *Queries) UnifiedSearch(ctx context.Context, arg UnifiedSearchParams) ([]UnifiedSearchRow, error) {
	rows, err := q.db.Query(ctx, unifiedSearch,
		arg.Lim,
		arg.Query,
		arg.ProjectID,
		arg.IncludeTask,
		arg.IncludeDocument,
		arg.IncludeArchNode,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UnifiedSearchRow{}
	for rows.Next() {
		var i UnifiedSearchRow
		if err := rows.Scan(
			&i.Kind,
			&i.ProjectID,
			&i.Rank,
			&i.Title,
			&i.Description,
			&i.TitleHeadline,
			&i.DescriptionHeadline,
			&i.TaskID,
			&i.DocPath,
			&i.DocScope,
			&i.NodeSlug,
			&i.NodeKind,
			&i.TaskState,
			&i.TaskType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
