// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package dbq

import (
	"context"
	"net/netip"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const deleteSessionByID = `-- name: DeleteSessionByID :exec
DELETE FROM sessions WHERE id = $1
`

func (q *Queries) DeleteSessionByID(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteSessionByID, id)
	return err
}

const getActiveSession = `-- name: GetActiveSession :one
SELECT id, user_id, created_at, last_seen_at, expires_at,
       COALESCE(user_agent, '')::text AS user_agent,
       COALESCE(host(ip), '')::text   AS ip
FROM sessions
WHERE id = $1 AND expires_at > now()
`

type GetActiveSessionRow struct {
	ID         uuid.UUID
	UserID     uuid.UUID
	CreatedAt  pgtype.Timestamptz
	LastSeenAt pgtype.Timestamptz
	ExpiresAt  pgtype.Timestamptz
	UserAgent  string
	Ip         string
}

func (q *Queries) GetActiveSession(ctx context.Context, id uuid.UUID) (GetActiveSessionRow, error) {
	row := q.db.QueryRow(ctx, getActiveSession, id)
	var i GetActiveSessionRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.ExpiresAt,
		&i.UserAgent,
		&i.Ip,
	)
	return i, err
}

const insertSession = `-- name: InsertSession :one
INSERT INTO sessions (user_id, expires_at, user_agent, ip)
VALUES ($1, $2, $3, $4::inet)
RETURNING id, user_id, created_at, last_seen_at, expires_at,
          COALESCE(user_agent, '')::text AS user_agent,
          COALESCE(host(ip), '')::text   AS ip
`

type InsertSessionParams struct {
	UserID    uuid.UUID
	ExpiresAt pgtype.Timestamptz
	UserAgent pgtype.Text
	Ip        *netip.Addr
}

type InsertSessionRow struct {
	ID         uuid.UUID
	UserID     uuid.UUID
	CreatedAt  pgtype.Timestamptz
	LastSeenAt pgtype.Timestamptz
	ExpiresAt  pgtype.Timestamptz
	UserAgent  string
	Ip         string
}

func (q *Queries) InsertSession(ctx context.Context, arg InsertSessionParams) (InsertSessionRow, error) {
	row := q.db.QueryRow(ctx, insertSession,
		arg.UserID,
		arg.ExpiresAt,
		arg.UserAgent,
		arg.Ip,
	)
	var i InsertSessionRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.ExpiresAt,
		&i.UserAgent,
		&i.Ip,
	)
	return i, err
}

const touchSessionLastSeen = `-- name: TouchSessionLastSeen :exec
UPDATE sessions SET last_seen_at = now() WHERE id = $1
`

func (q *Queries) TouchSessionLastSeen(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, touchSessionLastSeen, id)
	return err
}
