// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: skill.sql

package dbq

import (
	"context"
)

const getSkillOverride = `-- name: GetSkillOverride :one
SELECT content_md, frontmatter FROM documents
WHERE scope = 'global'
  AND kind = 'skill'
  AND deleted_at IS NULL
  AND path = $1::text
`

type GetSkillOverrideRow struct {
	ContentMd   string
	Frontmatter []byte
}

// Reads the body and frontmatter of a single skill-override document
// keyed by its full path (e.g. 'global/skills/domains/tasks.md').
// Returns ErrNoRows when there is no override for that path.
func (q *Queries) GetSkillOverride(ctx context.Context, path string) (GetSkillOverrideRow, error) {
	row := q.db.QueryRow(ctx, getSkillOverride, path)
	var i GetSkillOverrideRow
	err := row.Scan(&i.ContentMd, &i.Frontmatter)
	return i, err
}

const listSkillOverridePaths = `-- name: ListSkillOverridePaths :many
SELECT path FROM documents
WHERE scope = 'global'
  AND kind = 'skill'
  AND deleted_at IS NULL
  AND path LIKE $1::text
`

// Lists every global-scope skill document path. The skill bundle
// consults this list to union embedded files with user-provided
// overrides; returned paths still include the 'global/skills/' prefix
// and the caller trims it.
func (q *Queries) ListSkillOverridePaths(ctx context.Context, pathPrefix string) ([]string, error) {
	rows, err := q.db.Query(ctx, listSkillOverridePaths, pathPrefix)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var path string
		if err := rows.Scan(&path); err != nil {
			return nil, err
		}
		items = append(items, path)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
