// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: task_comments_commits.sql

package dbq

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const deleteTaskComment = `-- name: DeleteTaskComment :execrows
DELETE FROM task_comments WHERE id = $1
`

func (q *Queries) DeleteTaskComment(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteTaskComment, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteTaskCommit = `-- name: DeleteTaskCommit :exec
DELETE FROM task_commits WHERE task_id = $1 AND repo = $2 AND sha = $3
`

type DeleteTaskCommitParams struct {
	TaskID uuid.UUID
	Repo   string
	Sha    string
}

func (q *Queries) DeleteTaskCommit(ctx context.Context, arg DeleteTaskCommitParams) error {
	_, err := q.db.Exec(ctx, deleteTaskCommit, arg.TaskID, arg.Repo, arg.Sha)
	return err
}

const getTaskComment = `-- name: GetTaskComment :one
SELECT id, task_id, author_user_id, author_token_id, body_md,
       created_at, updated_at, edited_at, edited_by_user_id
FROM task_comments
WHERE id = $1
`

type GetTaskCommentRow struct {
	ID             uuid.UUID
	TaskID         uuid.UUID
	AuthorUserID   *uuid.UUID
	AuthorTokenID  *uuid.UUID
	BodyMd         string
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	EditedAt       pgtype.Timestamptz
	EditedByUserID *uuid.UUID
}

func (q *Queries) GetTaskComment(ctx context.Context, id uuid.UUID) (GetTaskCommentRow, error) {
	row := q.db.QueryRow(ctx, getTaskComment, id)
	var i GetTaskCommentRow
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.AuthorUserID,
		&i.AuthorTokenID,
		&i.BodyMd,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EditedAt,
		&i.EditedByUserID,
	)
	return i, err
}

const insertTaskComment = `-- name: InsertTaskComment :one
INSERT INTO task_comments (task_id, author_user_id, author_token_id, body_md)
VALUES ($1, $2, $3, $4)
RETURNING id, task_id, author_user_id, author_token_id, body_md,
          created_at, updated_at, edited_at, edited_by_user_id
`

type InsertTaskCommentParams struct {
	TaskID        uuid.UUID
	AuthorUserID  *uuid.UUID
	AuthorTokenID *uuid.UUID
	BodyMd        string
}

type InsertTaskCommentRow struct {
	ID             uuid.UUID
	TaskID         uuid.UUID
	AuthorUserID   *uuid.UUID
	AuthorTokenID  *uuid.UUID
	BodyMd         string
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	EditedAt       pgtype.Timestamptz
	EditedByUserID *uuid.UUID
}

func (q *Queries) InsertTaskComment(ctx context.Context, arg InsertTaskCommentParams) (InsertTaskCommentRow, error) {
	row := q.db.QueryRow(ctx, insertTaskComment,
		arg.TaskID,
		arg.AuthorUserID,
		arg.AuthorTokenID,
		arg.BodyMd,
	)
	var i InsertTaskCommentRow
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.AuthorUserID,
		&i.AuthorTokenID,
		&i.BodyMd,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EditedAt,
		&i.EditedByUserID,
	)
	return i, err
}

const listTaskComments = `-- name: ListTaskComments :many
SELECT id, task_id, author_user_id, author_token_id, body_md,
       created_at, updated_at, edited_at, edited_by_user_id
FROM task_comments
WHERE task_id = $1
ORDER BY created_at ASC
`

type ListTaskCommentsRow struct {
	ID             uuid.UUID
	TaskID         uuid.UUID
	AuthorUserID   *uuid.UUID
	AuthorTokenID  *uuid.UUID
	BodyMd         string
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	EditedAt       pgtype.Timestamptz
	EditedByUserID *uuid.UUID
}

func (q *Queries) ListTaskComments(ctx context.Context, taskID uuid.UUID) ([]ListTaskCommentsRow, error) {
	rows, err := q.db.Query(ctx, listTaskComments, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTaskCommentsRow{}
	for rows.Next() {
		var i ListTaskCommentsRow
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.AuthorUserID,
			&i.AuthorTokenID,
			&i.BodyMd,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.EditedAt,
			&i.EditedByUserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTaskCommits = `-- name: ListTaskCommits :many
SELECT task_id, repo, sha, message, added_at
FROM task_commits
WHERE task_id = $1
ORDER BY added_at DESC
`

type ListTaskCommitsRow struct {
	TaskID  uuid.UUID
	Repo    string
	Sha     string
	Message string
	AddedAt pgtype.Timestamptz
}

func (q *Queries) ListTaskCommits(ctx context.Context, taskID uuid.UUID) ([]ListTaskCommitsRow, error) {
	rows, err := q.db.Query(ctx, listTaskCommits, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTaskCommitsRow{}
	for rows.Next() {
		var i ListTaskCommitsRow
		if err := rows.Scan(
			&i.TaskID,
			&i.Repo,
			&i.Sha,
			&i.Message,
			&i.AddedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTaskComment = `-- name: UpdateTaskComment :one
UPDATE task_comments SET
  body_md = $2::text,
  edited_at = CASE WHEN $2::text <> body_md THEN now() ELSE edited_at END,
  edited_by_user_id = CASE WHEN $2::text <> body_md
                           THEN $3::uuid
                           ELSE edited_by_user_id END,
  updated_at = now()
WHERE id = $1
  AND ($4::timestamptz IS NULL
       OR updated_at = $4::timestamptz)
RETURNING id, task_id, author_user_id, author_token_id, body_md,
          created_at, updated_at, edited_at, edited_by_user_id
`

type UpdateTaskCommentParams struct {
	ID                uuid.UUID
	BodyMd            string
	CallerUserID      uuid.UUID
	ExpectedUpdatedAt pgtype.Timestamptz
}

type UpdateTaskCommentRow struct {
	ID             uuid.UUID
	TaskID         uuid.UUID
	AuthorUserID   *uuid.UUID
	AuthorTokenID  *uuid.UUID
	BodyMd         string
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	EditedAt       pgtype.Timestamptz
	EditedByUserID *uuid.UUID
}

// Edits a comment body with optimistic concurrency. Returns the updated
// row when the expected `updated_at` matches the row's current value;
// returns no rows otherwise so the caller can answer 409.
//
// Sets edited_at / edited_by_user_id whenever the body actually
// changes (a no-op edit doesn't paint the row as edited).
func (q *Queries) UpdateTaskComment(ctx context.Context, arg UpdateTaskCommentParams) (UpdateTaskCommentRow, error) {
	row := q.db.QueryRow(ctx, updateTaskComment,
		arg.ID,
		arg.BodyMd,
		arg.CallerUserID,
		arg.ExpectedUpdatedAt,
	)
	var i UpdateTaskCommentRow
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.AuthorUserID,
		&i.AuthorTokenID,
		&i.BodyMd,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EditedAt,
		&i.EditedByUserID,
	)
	return i, err
}

const upsertTaskCommit = `-- name: UpsertTaskCommit :exec
INSERT INTO task_commits (task_id, repo, sha, message, added_by_user_id, added_by_token_id)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (task_id, repo, sha) DO UPDATE SET message = EXCLUDED.message
`

type UpsertTaskCommitParams struct {
	TaskID         uuid.UUID
	Repo           string
	Sha            string
	Message        string
	AddedByUserID  *uuid.UUID
	AddedByTokenID *uuid.UUID
}

func (q *Queries) UpsertTaskCommit(ctx context.Context, arg UpsertTaskCommitParams) error {
	_, err := q.db.Exec(ctx, upsertTaskCommit,
		arg.TaskID,
		arg.Repo,
		arg.Sha,
		arg.Message,
		arg.AddedByUserID,
		arg.AddedByTokenID,
	)
	return err
}
