// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tasks.sql

package dbq

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countNonDoneChildren = `-- name: CountNonDoneChildren :one
SELECT COUNT(*)::int FROM tasks
WHERE parent_task_id = $1 AND state <> 'done'
`

func (q *Queries) CountNonDoneChildren(ctx context.Context, parentTaskID *uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, countNonDoneChildren, parentTaskID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const deleteTask = `-- name: DeleteTask :execrows
DELETE FROM tasks WHERE id = $1
`

func (q *Queries) DeleteTask(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteTask, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getParentStateAndGrandparent = `-- name: GetParentStateAndGrandparent :one
SELECT state, parent_task_id FROM tasks WHERE id = $1 FOR UPDATE
`

type GetParentStateAndGrandparentRow struct {
	State        string
	ParentTaskID *uuid.UUID
}

func (q *Queries) GetParentStateAndGrandparent(ctx context.Context, id uuid.UUID) (GetParentStateAndGrandparentRow, error) {
	row := q.db.QueryRow(ctx, getParentStateAndGrandparent, id)
	var i GetParentStateAndGrandparentRow
	err := row.Scan(&i.State, &i.ParentTaskID)
	return i, err
}

const getTask = `-- name: GetTask :one
SELECT id, project_id, parent_task_id, type, title, description_md,
       state, priority, assignee_user_id, target_role_id,
       actual_start, actual_end,
       created_by_user_id, created_by_token_id,
       created_at, updated_at
FROM tasks
WHERE id = $1
`

type GetTaskRow struct {
	ID               uuid.UUID
	ProjectID        uuid.UUID
	ParentTaskID     *uuid.UUID
	Type             string
	Title            string
	DescriptionMd    string
	State            string
	Priority         int32
	AssigneeUserID   *uuid.UUID
	TargetRoleID     *uuid.UUID
	ActualStart      pgtype.Timestamptz
	ActualEnd        pgtype.Timestamptz
	CreatedByUserID  *uuid.UUID
	CreatedByTokenID *uuid.UUID
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}

func (q *Queries) GetTask(ctx context.Context, id uuid.UUID) (GetTaskRow, error) {
	row := q.db.QueryRow(ctx, getTask, id)
	var i GetTaskRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.ParentTaskID,
		&i.Type,
		&i.Title,
		&i.DescriptionMd,
		&i.State,
		&i.Priority,
		&i.AssigneeUserID,
		&i.TargetRoleID,
		&i.ActualStart,
		&i.ActualEnd,
		&i.CreatedByUserID,
		&i.CreatedByTokenID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertTask = `-- name: InsertTask :one
INSERT INTO tasks (
  project_id, parent_task_id, type, title, description_md,
  state, priority, assignee_user_id, target_role_id,
  created_by_user_id, created_by_token_id
)
VALUES ($1, $2, $3, $4, $5, 'todo', $6, $7, $8, $9, $10)
RETURNING id, project_id, parent_task_id, type, title, description_md,
          state, priority, assignee_user_id, target_role_id,
          actual_start, actual_end,
          created_by_user_id, created_by_token_id,
          created_at, updated_at
`

type InsertTaskParams struct {
	ProjectID        uuid.UUID
	ParentTaskID     *uuid.UUID
	Type             string
	Title            string
	DescriptionMd    string
	Priority         int32
	AssigneeUserID   *uuid.UUID
	TargetRoleID     *uuid.UUID
	CreatedByUserID  *uuid.UUID
	CreatedByTokenID *uuid.UUID
}

type InsertTaskRow struct {
	ID               uuid.UUID
	ProjectID        uuid.UUID
	ParentTaskID     *uuid.UUID
	Type             string
	Title            string
	DescriptionMd    string
	State            string
	Priority         int32
	AssigneeUserID   *uuid.UUID
	TargetRoleID     *uuid.UUID
	ActualStart      pgtype.Timestamptz
	ActualEnd        pgtype.Timestamptz
	CreatedByUserID  *uuid.UUID
	CreatedByTokenID *uuid.UUID
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}

func (q *Queries) InsertTask(ctx context.Context, arg InsertTaskParams) (InsertTaskRow, error) {
	row := q.db.QueryRow(ctx, insertTask,
		arg.ProjectID,
		arg.ParentTaskID,
		arg.Type,
		arg.Title,
		arg.DescriptionMd,
		arg.Priority,
		arg.AssigneeUserID,
		arg.TargetRoleID,
		arg.CreatedByUserID,
		arg.CreatedByTokenID,
	)
	var i InsertTaskRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.ParentTaskID,
		&i.Type,
		&i.Title,
		&i.DescriptionMd,
		&i.State,
		&i.Priority,
		&i.AssigneeUserID,
		&i.TargetRoleID,
		&i.ActualStart,
		&i.ActualEnd,
		&i.CreatedByUserID,
		&i.CreatedByTokenID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listUnresolvedPreconditions = `-- name: ListUnresolvedPreconditions :many
SELECT t.id, t.title, t.state
FROM task_dependencies td
JOIN tasks t ON t.id = td.depends_on_id
WHERE td.task_id = $1 AND t.state <> 'done'
ORDER BY t.actual_end NULLS LAST, t.created_at
`

type ListUnresolvedPreconditionsRow struct {
	ID    uuid.UUID
	Title string
	State string
}

func (q *Queries) ListUnresolvedPreconditions(ctx context.Context, taskID uuid.UUID) ([]ListUnresolvedPreconditionsRow, error) {
	rows, err := q.db.Query(ctx, listUnresolvedPreconditions, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUnresolvedPreconditionsRow{}
	for rows.Next() {
		var i ListUnresolvedPreconditionsRow
		if err := rows.Scan(&i.ID, &i.Title, &i.State); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockTaskTypeAndParent = `-- name: LockTaskTypeAndParent :one
SELECT type, parent_task_id FROM tasks WHERE id = $1 FOR UPDATE
`

type LockTaskTypeAndParentRow struct {
	Type         string
	ParentTaskID *uuid.UUID
}

func (q *Queries) LockTaskTypeAndParent(ctx context.Context, id uuid.UUID) (LockTaskTypeAndParentRow, error) {
	row := q.db.QueryRow(ctx, lockTaskTypeAndParent, id)
	var i LockTaskTypeAndParentRow
	err := row.Scan(&i.Type, &i.ParentTaskID)
	return i, err
}

const roleExistsInProject = `-- name: RoleExistsInProject :one
SELECT EXISTS (SELECT 1 FROM roles WHERE id = $1 AND project_id = $2)::bool
`

type RoleExistsInProjectParams struct {
	ID        uuid.UUID
	ProjectID uuid.UUID
}

func (q *Queries) RoleExistsInProject(ctx context.Context, arg RoleExistsInProjectParams) (bool, error) {
	row := q.db.QueryRow(ctx, roleExistsInProject, arg.ID, arg.ProjectID)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const setTaskDoing = `-- name: SetTaskDoing :exec
UPDATE tasks SET
  state = 'doing',
  actual_start = COALESCE(actual_start, now()),
  actual_end = NULL,
  updated_at = now()
WHERE id = $1
`

func (q *Queries) SetTaskDoing(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, setTaskDoing, id)
	return err
}

const setTaskDone = `-- name: SetTaskDone :exec
UPDATE tasks SET
  state = 'done',
  actual_start = COALESCE(actual_start, now()),
  actual_end = now(),
  updated_at = now()
WHERE id = $1
`

func (q *Queries) SetTaskDone(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, setTaskDone, id)
	return err
}

const setTaskTodo = `-- name: SetTaskTodo :exec
UPDATE tasks SET
  state = 'todo',
  actual_start = NULL,
  actual_end = NULL,
  updated_at = now()
WHERE id = $1
`

func (q *Queries) SetTaskTodo(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, setTaskTodo, id)
	return err
}

const userBelongsToProjectOrIsAdmin = `-- name: UserBelongsToProjectOrIsAdmin :one
SELECT (
  EXISTS (SELECT 1 FROM users WHERE id = $1 AND is_admin = true)
  OR EXISTS (SELECT 1 FROM memberships WHERE user_id = $1 AND project_id = $2)
)::bool
`

type UserBelongsToProjectOrIsAdminParams struct {
	ID        uuid.UUID
	ProjectID uuid.UUID
}

func (q *Queries) UserBelongsToProjectOrIsAdmin(ctx context.Context, arg UserBelongsToProjectOrIsAdminParams) (bool, error) {
	row := q.db.QueryRow(ctx, userBelongsToProjectOrIsAdmin, arg.ID, arg.ProjectID)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}
