// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: task_comments_commits.sql

package dbq

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const deleteTaskCommit = `-- name: DeleteTaskCommit :exec
DELETE FROM task_commits WHERE task_id = $1 AND repo = $2 AND sha = $3
`

type DeleteTaskCommitParams struct {
	TaskID uuid.UUID
	Repo   string
	Sha    string
}

func (q *Queries) DeleteTaskCommit(ctx context.Context, arg DeleteTaskCommitParams) error {
	_, err := q.db.Exec(ctx, deleteTaskCommit, arg.TaskID, arg.Repo, arg.Sha)
	return err
}

const insertTaskComment = `-- name: InsertTaskComment :one
INSERT INTO task_comments (task_id, author_user_id, author_token_id, body_md)
VALUES ($1, $2, $3, $4)
RETURNING id, task_id, author_user_id, author_token_id, body_md, created_at
`

type InsertTaskCommentParams struct {
	TaskID        uuid.UUID
	AuthorUserID  *uuid.UUID
	AuthorTokenID *uuid.UUID
	BodyMd        string
}

func (q *Queries) InsertTaskComment(ctx context.Context, arg InsertTaskCommentParams) (TaskComment, error) {
	row := q.db.QueryRow(ctx, insertTaskComment,
		arg.TaskID,
		arg.AuthorUserID,
		arg.AuthorTokenID,
		arg.BodyMd,
	)
	var i TaskComment
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.AuthorUserID,
		&i.AuthorTokenID,
		&i.BodyMd,
		&i.CreatedAt,
	)
	return i, err
}

const listTaskComments = `-- name: ListTaskComments :many
SELECT id, task_id, author_user_id, author_token_id, body_md, created_at
FROM task_comments
WHERE task_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListTaskComments(ctx context.Context, taskID uuid.UUID) ([]TaskComment, error) {
	rows, err := q.db.Query(ctx, listTaskComments, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TaskComment{}
	for rows.Next() {
		var i TaskComment
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.AuthorUserID,
			&i.AuthorTokenID,
			&i.BodyMd,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTaskCommits = `-- name: ListTaskCommits :many
SELECT task_id, repo, sha, message, added_at
FROM task_commits
WHERE task_id = $1
ORDER BY added_at DESC
`

type ListTaskCommitsRow struct {
	TaskID  uuid.UUID
	Repo    string
	Sha     string
	Message string
	AddedAt pgtype.Timestamptz
}

func (q *Queries) ListTaskCommits(ctx context.Context, taskID uuid.UUID) ([]ListTaskCommitsRow, error) {
	rows, err := q.db.Query(ctx, listTaskCommits, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTaskCommitsRow{}
	for rows.Next() {
		var i ListTaskCommitsRow
		if err := rows.Scan(
			&i.TaskID,
			&i.Repo,
			&i.Sha,
			&i.Message,
			&i.AddedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertTaskCommit = `-- name: UpsertTaskCommit :exec
INSERT INTO task_commits (task_id, repo, sha, message, added_by_user_id, added_by_token_id)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (task_id, repo, sha) DO UPDATE SET message = EXCLUDED.message
`

type UpsertTaskCommitParams struct {
	TaskID         uuid.UUID
	Repo           string
	Sha            string
	Message        string
	AddedByUserID  *uuid.UUID
	AddedByTokenID *uuid.UUID
}

func (q *Queries) UpsertTaskCommit(ctx context.Context, arg UpsertTaskCommitParams) error {
	_, err := q.db.Exec(ctx, upsertTaskCommit,
		arg.TaskID,
		arg.Repo,
		arg.Sha,
		arg.Message,
		arg.AddedByUserID,
		arg.AddedByTokenID,
	)
	return err
}
