// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tokens.sql

package dbq

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getAPIToken = `-- name: GetAPIToken :one
SELECT id, user_id, project_id, name, prefix, default_role_id,
       created_at, last_used_at, revoked_at
FROM api_tokens
WHERE id = $1
`

type GetAPITokenRow struct {
	ID            uuid.UUID
	UserID        uuid.UUID
	ProjectID     uuid.UUID
	Name          string
	Prefix        string
	DefaultRoleID *uuid.UUID
	CreatedAt     pgtype.Timestamptz
	LastUsedAt    pgtype.Timestamptz
	RevokedAt     pgtype.Timestamptz
}

func (q *Queries) GetAPIToken(ctx context.Context, id uuid.UUID) (GetAPITokenRow, error) {
	row := q.db.QueryRow(ctx, getAPIToken, id)
	var i GetAPITokenRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProjectID,
		&i.Name,
		&i.Prefix,
		&i.DefaultRoleID,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.RevokedAt,
	)
	return i, err
}

const insertAPIToken = `-- name: InsertAPIToken :one
INSERT INTO api_tokens (user_id, project_id, name, token_hash, prefix, default_role_id)
VALUES (
    $1::uuid,
    $2::uuid,
    $3::text,
    $4::bytea,
    $5::text,
    $6::uuid
)
RETURNING id, user_id, project_id, name, prefix, default_role_id,
          created_at, last_used_at, revoked_at
`

type InsertAPITokenParams struct {
	UserID        uuid.UUID
	ProjectID     uuid.UUID
	Name          string
	TokenHash     []byte
	Prefix        string
	DefaultRoleID *uuid.UUID
}

type InsertAPITokenRow struct {
	ID            uuid.UUID
	UserID        uuid.UUID
	ProjectID     uuid.UUID
	Name          string
	Prefix        string
	DefaultRoleID *uuid.UUID
	CreatedAt     pgtype.Timestamptz
	LastUsedAt    pgtype.Timestamptz
	RevokedAt     pgtype.Timestamptz
}

func (q *Queries) InsertAPIToken(ctx context.Context, arg InsertAPITokenParams) (InsertAPITokenRow, error) {
	row := q.db.QueryRow(ctx, insertAPIToken,
		arg.UserID,
		arg.ProjectID,
		arg.Name,
		arg.TokenHash,
		arg.Prefix,
		arg.DefaultRoleID,
	)
	var i InsertAPITokenRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProjectID,
		&i.Name,
		&i.Prefix,
		&i.DefaultRoleID,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.RevokedAt,
	)
	return i, err
}

const listProjectTokens = `-- name: ListProjectTokens :many
SELECT id, user_id, project_id, name, prefix, default_role_id,
       created_at, last_used_at, revoked_at
FROM api_tokens
WHERE project_id = $1
ORDER BY created_at DESC
`

type ListProjectTokensRow struct {
	ID            uuid.UUID
	UserID        uuid.UUID
	ProjectID     uuid.UUID
	Name          string
	Prefix        string
	DefaultRoleID *uuid.UUID
	CreatedAt     pgtype.Timestamptz
	LastUsedAt    pgtype.Timestamptz
	RevokedAt     pgtype.Timestamptz
}

func (q *Queries) ListProjectTokens(ctx context.Context, projectID uuid.UUID) ([]ListProjectTokensRow, error) {
	rows, err := q.db.Query(ctx, listProjectTokens, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProjectTokensRow{}
	for rows.Next() {
		var i ListProjectTokensRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ProjectID,
			&i.Name,
			&i.Prefix,
			&i.DefaultRoleID,
			&i.CreatedAt,
			&i.LastUsedAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lookupAPIToken = `-- name: LookupAPIToken :one
SELECT t.id AS token_id, t.user_id, t.project_id, t.name AS token_name,
       t.prefix, t.default_role_id,
       t.created_at AS token_created_at,
       t.last_used_at, t.revoked_at,
       u.id AS user_id_full, u.github_login, u.github_id, u.display_name,
       COALESCE(u.avatar_url, '')::text AS avatar_url,
       u.is_admin, u.created_at AS user_created_at, u.last_seen_at
FROM api_tokens t
JOIN users u ON u.id = t.user_id
WHERE t.token_hash = $1 AND t.revoked_at IS NULL
`

type LookupAPITokenRow struct {
	TokenID        uuid.UUID
	UserID         uuid.UUID
	ProjectID      uuid.UUID
	TokenName      string
	Prefix         string
	DefaultRoleID  *uuid.UUID
	TokenCreatedAt pgtype.Timestamptz
	LastUsedAt     pgtype.Timestamptz
	RevokedAt      pgtype.Timestamptz
	UserIDFull     uuid.UUID
	GithubLogin    string
	GithubID       int64
	DisplayName    string
	AvatarUrl      string
	IsAdmin        bool
	UserCreatedAt  pgtype.Timestamptz
	LastSeenAt     pgtype.Timestamptz
}

func (q *Queries) LookupAPIToken(ctx context.Context, tokenHash []byte) (LookupAPITokenRow, error) {
	row := q.db.QueryRow(ctx, lookupAPIToken, tokenHash)
	var i LookupAPITokenRow
	err := row.Scan(
		&i.TokenID,
		&i.UserID,
		&i.ProjectID,
		&i.TokenName,
		&i.Prefix,
		&i.DefaultRoleID,
		&i.TokenCreatedAt,
		&i.LastUsedAt,
		&i.RevokedAt,
		&i.UserIDFull,
		&i.GithubLogin,
		&i.GithubID,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.IsAdmin,
		&i.UserCreatedAt,
		&i.LastSeenAt,
	)
	return i, err
}

const revokeAPIToken = `-- name: RevokeAPIToken :execrows
UPDATE api_tokens
SET revoked_at = now()
WHERE id = $1
  AND revoked_at IS NULL
  AND ($2::bool OR user_id = $3::uuid)
`

type RevokeAPITokenParams struct {
	ID              uuid.UUID
	IsAdmin         bool
	RequesterUserID uuid.UUID
}

func (q *Queries) RevokeAPIToken(ctx context.Context, arg RevokeAPITokenParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeAPIToken, arg.ID, arg.IsAdmin, arg.RequesterUserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const touchTokenLastUsed = `-- name: TouchTokenLastUsed :exec
UPDATE api_tokens SET last_used_at = now() WHERE id = $1
`

func (q *Queries) TouchTokenLastUsed(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, touchTokenLastUsed, id)
	return err
}
