// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package dbq

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countUsers = `-- name: CountUsers :one
SELECT COUNT(*)::int FROM users
`

func (q *Queries) CountUsers(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, countUsers)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const getUserByGithubID = `-- name: GetUserByGithubID :one
SELECT id, github_login, github_id, display_name,
       COALESCE(avatar_url, '')::text AS avatar_url,
       is_admin, created_at, last_seen_at
FROM users
WHERE github_id = $1
`

type GetUserByGithubIDRow struct {
	ID          uuid.UUID
	GithubLogin string
	GithubID    int64
	DisplayName string
	AvatarUrl   string
	IsAdmin     bool
	CreatedAt   pgtype.Timestamptz
	LastSeenAt  pgtype.Timestamptz
}

func (q *Queries) GetUserByGithubID(ctx context.Context, githubID int64) (GetUserByGithubIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByGithubID, githubID)
	var i GetUserByGithubIDRow
	err := row.Scan(
		&i.ID,
		&i.GithubLogin,
		&i.GithubID,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.IsAdmin,
		&i.CreatedAt,
		&i.LastSeenAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, github_login, github_id, display_name,
       COALESCE(avatar_url, '')::text AS avatar_url,
       is_admin, created_at, last_seen_at
FROM users WHERE id = $1
`

type GetUserByIDRow struct {
	ID          uuid.UUID
	GithubLogin string
	GithubID    int64
	DisplayName string
	AvatarUrl   string
	IsAdmin     bool
	CreatedAt   pgtype.Timestamptz
	LastSeenAt  pgtype.Timestamptz
}

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (GetUserByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.GithubLogin,
		&i.GithubID,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.IsAdmin,
		&i.CreatedAt,
		&i.LastSeenAt,
	)
	return i, err
}

const insertUser = `-- name: InsertUser :one
INSERT INTO users (github_login, github_id, display_name, avatar_url, is_admin)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, github_login, github_id, display_name,
          COALESCE(avatar_url, '')::text AS avatar_url,
          is_admin, created_at, last_seen_at
`

type InsertUserParams struct {
	GithubLogin string
	GithubID    int64
	DisplayName string
	AvatarUrl   pgtype.Text
	IsAdmin     bool
}

type InsertUserRow struct {
	ID          uuid.UUID
	GithubLogin string
	GithubID    int64
	DisplayName string
	AvatarUrl   string
	IsAdmin     bool
	CreatedAt   pgtype.Timestamptz
	LastSeenAt  pgtype.Timestamptz
}

func (q *Queries) InsertUser(ctx context.Context, arg InsertUserParams) (InsertUserRow, error) {
	row := q.db.QueryRow(ctx, insertUser,
		arg.GithubLogin,
		arg.GithubID,
		arg.DisplayName,
		arg.AvatarUrl,
		arg.IsAdmin,
	)
	var i InsertUserRow
	err := row.Scan(
		&i.ID,
		&i.GithubLogin,
		&i.GithubID,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.IsAdmin,
		&i.CreatedAt,
		&i.LastSeenAt,
	)
	return i, err
}

const touchUserLastSeen = `-- name: TouchUserLastSeen :exec
UPDATE users SET last_seen_at = now() WHERE id = $1
`

func (q *Queries) TouchUserLastSeen(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, touchUserLastSeen, id)
	return err
}

const updateUserProfile = `-- name: UpdateUserProfile :exec
UPDATE users
SET display_name = $2, avatar_url = $3, github_login = $4
WHERE id = $1
`

type UpdateUserProfileParams struct {
	ID          uuid.UUID
	DisplayName string
	AvatarUrl   pgtype.Text
	GithubLogin string
}

func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) error {
	_, err := q.db.Exec(ctx, updateUserProfile,
		arg.ID,
		arg.DisplayName,
		arg.AvatarUrl,
		arg.GithubLogin,
	)
	return err
}
